// svelte/src/lib/users/ui/UserButton.svelte
<script lang="ts">
	// Primitives
	import * as Popover from '$lib/primitives/ui/popover';
	import * as Dialog from '$lib/primitives/ui/dialog';
	import { Avatar } from '@skeletonlabs/skeleton-svelte';
	// Icons
	import ChevronRight from '@lucide/svelte/icons/chevron-right';
	// Components
	import UserProfile from '$lib/users/ui/UserProfile.svelte';

	// API
	import { useAuth } from '@mmailaender/convex-auth-svelte/sveltekit';
	import { useQuery } from 'convex-svelte';
	import { api } from '$convex/_generated/api';

	// Types
	import type { ComponentProps } from 'svelte';
	type PopoverProps = ComponentProps<typeof Popover.Content>;
	import type { FunctionReturnType } from 'convex/server';
	type UserResponse = FunctionReturnType<typeof api.users.queries.getUser>;

	// Props
	const {
		popoverSide = 'bottom',
		popoverAlign = 'end',
		initialData
	}: {
		popoverSide?: PopoverProps['side'];
		popoverAlign?: PopoverProps['align'];
		initialData?: UserResponse;
	} = $props();

	// State
	let userPopoverOpen: boolean = $state(false);
	let profileDialogOpen: boolean = $state(false);

	// Auth
	const { signOut } = useAuth();
	const isAuthenticated = $derived(useAuth().isAuthenticated);

	// Queries
	const userResponse = useQuery(api.users.queries.getUser, {}, { initialData });
	const user = $derived(userResponse.data);

	/**
	 * Open profile modal and close popover
	 */
	function openProfileModal(): void {
		userPopoverOpen = false;
		profileDialogOpen = true;
	}
</script>

{#if isAuthenticated}
	{#if user}
		<!-- User Popover -->
		<Popover.Root bind:open={userPopoverOpen}>
			<Popover.Trigger>
				<Avatar
					src={user.image}
					name={user.name}
					size="size-10 ring-0 hover:ring-4 ring-surface-100-900 ease-out duration-200"
				/>
			</Popover.Trigger>

			<Popover.Content side={popoverSide} align={popoverAlign}>
				<div class="flex flex-col gap-1 p-0">
					<button
						class="bg-surface-50-950 hover:bg-surface-100-900 rounded-base flex flex-row items-center gap-3 p-3 pr-6 duration-200 ease-in-out"
						onclick={openProfileModal}
					>
						<Avatar src={user.image} name={user.name} size="size-12" />
						<div class="flex flex-1 flex-col gap-0 overflow-hidden">
							<p class="truncate text-left text-base font-medium">{user.name}</p>
							<p class="text-surface-700-300 truncate text-left text-xs">
								{user.email}
							</p>
						</div>
						<ChevronRight class="size-4" />
					</button>
					<button
						class="btn preset-faded-surface-50-950 hover:bg-surface-200-800 h-10 justify-between gap-1 text-sm"
						onclick={() => signOut()}
					>
						Sign out
					</button>
				</div>
			</Popover.Content>
		</Popover.Root>

		<!-- Profile Dialog -->
		<Dialog.Root bind:open={profileDialogOpen}>
			<Dialog.Content class="max-w-xl">
				<Dialog.Header>
					<Dialog.Title>Profile</Dialog.Title>
				</Dialog.Header>
				<UserProfile />
				<Dialog.CloseX />
			</Dialog.Content>
		</Dialog.Root>
	{:else}
		<div class="placeholder-circle size-10 animate-pulse"></div>
	{/if}
{:else}
	<a href="/signin" class="btn preset-filled-primary-500">Sign in</a>
{/if}

// nextjs/src/components/user/ui/widget/UserButton.tsx
"use client";

import { useState } from "react";
import { useAuthActions } from "@convex-dev/auth/react";
import { useQuery, Authenticated, Unauthenticated } from "convex/react";
import { Avatar } from "@skeletonlabs/skeleton-react";

import { api } from "@/convex/_generated/api";
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverTrigger,
} from "@/components/primitives/ui/Popover";
import {
  Modal,
  ModalClose,
  ModalContent,
} from "@/components/primitives/ui/Modal";

import UserProfile from "@/components/user/ui/page/UserProfile";

export default function UserButton() {
  const { signOut } = useAuthActions();
  const user = useQuery(api.users.getUser);
  const [open, setOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);

  return (
    <>
      <Authenticated>
        {user ? (
          <>
            <Popover open={open} onOpenChange={setOpen} placement="bottom-end">
              <PopoverTrigger onClick={() => setOpen((v) => !v)}>
                <Avatar src={user.image} name={user.name} size="size-10" />
              </PopoverTrigger>
              <PopoverContent>
                <PopoverDescription>
                  <ul role="list" className="space-y-1">
                    <li>
                      <div className="rounded-base text-surface-700-300 border-surface-700-300 flex gap-x-3 p-4 text-sm/6 font-semibold">
                        <Avatar
                          src={user.image}
                          name={user.name}
                          size="size-10"
                        />
                        <div className="flex max-w-90 flex-col gap-3">
                          <div className="flex-1">
                            <p className="font-medium">{user.name}</p>
                            <p className="text-sm">{user.email}</p>
                          </div>
                          <div className="flex space-x-2">
                            <button
                              className="btn preset-outlined-surface-500"
                              onClick={() => {
                                setOpen(false);
                                setProfileOpen(true);
                              }}
                            >
                              Manage account
                            </button>

                            <button
                              className="btn preset-outlined-surface-500"
                              onClick={() => void signOut()}
                            >
                              Sign out
                            </button>
                          </div>
                        </div>
                      </div>
                    </li>
                  </ul>
                </PopoverDescription>
              </PopoverContent>
            </Popover>

            {/* ProfileInfo Popup */}
            <Modal open={profileOpen} onOpenChange={setProfileOpen}>
              <ModalContent>
                <div className="flex justify-between items-center mb-4">
                  <UserProfile />
                  <ModalClose />
                </div>
              </ModalContent>
            </Modal>

            <div className="relative">
              <button
                className="btn preset-filled-primary-500"
                onClick={() => void signOut()}
              >
                Sign out
              </button>
            </div>
          </>
        ) : (
          <div className="placeholder-circle size-10 animate-pulse" />
        )}
      </Authenticated>
      <Unauthenticated>
        <a href="/login" className="btn preset-filled-primary-500">
          Sign in
        </a>
      </Unauthenticated>
    </>
  );
}
