// svelte/src/lib/users/ui/UserProfile.svelte
<script lang="ts">
	import ProfileInfo from '$lib/users/ui/ProfileInfo.svelte';
	import Emails from '$lib/users/ui/Emails.svelte';
	import DeleteUser from '$lib/users/ui/DeleteUser.svelte';
	import Accounts from './Accounts.svelte';
</script>

<div class="w-full">
	<div class="flex flex-col gap-3 pb-8">
		<ProfileInfo />

		<Emails />
	</div>

	<div class="flex h-full flex-col">
		<Accounts />
	</div>
	<div>
		<DeleteUser />
	</div>
</div>

// nextjs/src/components/user/ui/page/UserProfile.tsx
import ProfileInfo from "@/components/user/ui/widget/ProfileInfo";
import DeleteUser from "@/components/user/ui/widget/DeleteUser";

export default function UserProfile() {
  return (
    <div className="w-full p-6 md:w-3/4">
      <ProfileInfo />
      <div className="flex justify-end">
        <DeleteUser />
      </div>
    </div>
  );
}
