// nextjs/src/components/organizations/ui/MembersAndInvitations.tsx
/** UI **/
// Primitives
import * as Tabs from '@/components/primitives/ui/tabs';
import * as Dialog from '@/components/primitives/ui/dialog';
import * as Drawer from '@/components/primitives/ui/drawer';
// Icons
import { Plus } from 'lucide-react';
// Widgets
import Members from '@/components/organizations/ui/Members';
import Invitations from '@/components/organizations/ui/Invitations';
import InviteMembers from '@/components/organizations/ui/InviteMembers';

// API
import { useQuery } from 'convex/react';
import { api } from '@/convex/_generated/api';
import { useRoles } from '@/components/organizations/api/hooks';
import { useState } from 'react';

export default function MembersAndInvitations() {
	const activeOrganization = useQuery(api.organizations.queries.getActiveOrganization);
	const members = activeOrganization?.members;
	const invitationList = useQuery(api.organizations.invitations.queries.listInvitations);
	const isOwnerOrAdmin = useRoles().hasOwnerOrAdminRole;
	const [inviteMembersDialogOpen, setInviteMembersDialogOpen] = useState(false);
	const [inviteMembersDrawerOpen, setInviteMembersDrawerOpen] = useState(false);

	const handleInviteMembersSuccess = () => {
		setInviteMembersDialogOpen(false);
		setInviteMembersDrawerOpen(false);
	};

	return (
		<Tabs.Root defaultValue="members">
			<div className="border-surface-300-700 flex w-full flex-row justify-between border-b pb-6 align-middle">
				<Tabs.List className="flex-1 md:flex-initial">
					<Tabs.Trigger value="members" className="flex-1 gap-2 md:flex-initial">
						Members{' '}
						<span className="badge preset-filled-surface-300-700 size-6 rounded-full">
							{members && `${members.length}`}{' '}
						</span>
					</Tabs.Trigger>
					{isOwnerOrAdmin && (
						<Tabs.Trigger value="invitations" className="flex-1 gap-2 md:flex-initial">
							Invitations{' '}
							<span className="badge preset-filled-surface-300-700 size-6 rounded-full">
								{invitationList && `${invitationList.filter((i) => i.status === 'pending').length}`}
							</span>
						</Tabs.Trigger>
					)}
				</Tabs.List>
				{isOwnerOrAdmin && (
					<>
						<Dialog.Root open={inviteMembersDialogOpen} onOpenChange={setInviteMembersDialogOpen}>
							<Dialog.Trigger className="btn preset-filled-primary-500 hidden h-10 items-center gap-2 text-sm md:flex">
								<Plus className="size-5" />
								<span>Invite members</span>
							</Dialog.Trigger>
							<Dialog.Content className="max-w-108">
								<Dialog.Header>
									<Dialog.Title>Invite new members</Dialog.Title>
								</Dialog.Header>
								<InviteMembers onSuccess={handleInviteMembersSuccess} />
								<Dialog.CloseX />
							</Dialog.Content>
						</Dialog.Root>
						<Drawer.Root open={inviteMembersDrawerOpen} onOpenChange={setInviteMembersDrawerOpen}>
							<Drawer.Trigger className="btn preset-filled-primary-500 absolute right-4 bottom-4 z-10 h-10 text-sm md:hidden">
								<Plus className="size-5" /> Invite members
							</Drawer.Trigger>
							<Drawer.Content>
								<Drawer.Header>
									<Drawer.Title>Invite new members</Drawer.Title>
								</Drawer.Header>
								<InviteMembers onSuccess={handleInviteMembersSuccess} />
								<Drawer.CloseX />
							</Drawer.Content>
						</Drawer.Root>
					</>
				)}
			</div>
			<Tabs.Content value="members" className="">
				<Members />
			</Tabs.Content>
			{isOwnerOrAdmin && (
				<Tabs.Content value="invitations">
					<Invitations />
				</Tabs.Content>
			)}
		</Tabs.Root>
	);
}

// svelte/src/lib/organizations/ui/MembersAndInvitations.svelte
<script lang="ts">
	// Primitives
	import * as Tabs from '$lib/primitives/ui/tabs';
	import * as Dialog from '$lib/primitives/ui/dialog';
	import * as Drawer from '$lib/primitives/ui/drawer';
	// Icons
	import PlusIcon from '@lucide/svelte/icons/plus';
	// Components
	import Members from '$lib/organizations/ui/Members.svelte';
	import Invitations from '$lib/organizations/ui/Invitations.svelte';
	import InviteMembers from '$lib/organizations/ui/InviteMembers.svelte';

	// API
	import { useQuery } from 'convex-svelte';
	import { api } from '$convex/_generated/api';
	import { useRoles } from '$lib/organizations/api/roles.svelte';

	// API Types
	import type { FunctionReturnType } from 'convex/server';
	type ActiveOrganizationResponse = FunctionReturnType<
		typeof api.organizations.queries.getActiveOrganization
	>;
	type InvitationListResponse = FunctionReturnType<
		typeof api.organizations.invitations.queries.listInvitations
	>;

	// Props
	let {
		initialData
	}: {
		initialData?: {
			activeOrganization?: ActiveOrganizationResponse;
			invitationList?: InvitationListResponse;
		};
	} = $props();

	// Queries
	const activeOrganizationResponse = useQuery(
		api.organizations.queries.getActiveOrganization,
		{},
		{ initialData: initialData?.activeOrganization }
	);
	const invitationListResponse = useQuery(
		api.organizations.invitations.queries.listInvitations,
		{},
		{ initialData: initialData?.invitationList }
	);

	// Derived data
	const activeOrganization = $derived(activeOrganizationResponse.data);
	const members = $derived(activeOrganization?.members);
	const invitationList = $derived(invitationListResponse.data);
	const roles = useRoles();
	const isOwnerOrAdmin = $derived(roles.hasOwnerOrAdminRole);

	// State
	let inviteMembersDialogOpen = $state(false);
	let inviteMembersDrawerOpen = $state(false);

	// Handlers
	function handleInviteMembersSuccess() {
		inviteMembersDialogOpen = false;
		inviteMembersDrawerOpen = false;
	}
</script>

<Tabs.Root value="members">
	<div
		class="border-surface-300-700 flex w-full flex-row justify-between border-b pb-6 align-middle"
	>
		<Tabs.List class="flex-1 md:flex-initial">
			<Tabs.Trigger value="members" class="flex-1 gap-2 md:flex-initial">
				Members
				<span class="badge preset-filled-surface-300-700 size-6 rounded-full">
					{members && `${members.length}`}
				</span>
			</Tabs.Trigger>
			{#if isOwnerOrAdmin}
				<Tabs.Trigger value="invitations" class="flex-1 gap-2 md:flex-initial">
					Invitations
					<span class="badge preset-filled-surface-300-700 size-6 rounded-full">
						{invitationList && `${invitationList.filter((i) => i.status === 'pending').length}`}
					</span>
				</Tabs.Trigger>
			{/if}
		</Tabs.List>
		{#if isOwnerOrAdmin}
			<Dialog.Root bind:open={inviteMembersDialogOpen}>
				<Dialog.Trigger
					class="btn preset-filled-primary-500 hidden h-10 items-center gap-2 text-sm md:flex"
				>
					<PlusIcon class="size-5" />
					<span>Invite members</span>
				</Dialog.Trigger>
				<Dialog.Content class="max-w-100">
					<Dialog.Header>
						<Dialog.Title>Invite new members</Dialog.Title>
					</Dialog.Header>
					<InviteMembers onSuccess={handleInviteMembersSuccess} />
					<Dialog.CloseX />
				</Dialog.Content>
			</Dialog.Root>
			<Drawer.Root bind:open={inviteMembersDrawerOpen}>
				<Drawer.Trigger
					class="btn preset-filled-primary-500 absolute right-4 bottom-4 z-10 h-10 text-sm md:hidden"
				>
					<PlusIcon class="size-5" /> Invite members
				</Drawer.Trigger>
				<Drawer.Content>
					<Drawer.Header>
						<Drawer.Title>Invite new members</Drawer.Title>
					</Drawer.Header>
					<InviteMembers onSuccess={handleInviteMembersSuccess} />
					<Drawer.CloseX />
				</Drawer.Content>
			</Drawer.Root>
		{/if}
	</div>

	<Tabs.Content value="members">
		<Members />
	</Tabs.Content>

	{#if isOwnerOrAdmin}
		<Tabs.Content value="invitations">
			<Invitations />
		</Tabs.Content>
	{/if}
</Tabs.Root>
