// nextjs/src/components/organizations/ui/widget/MembersAndInvitations.tsx
import { useState } from "react";
import { Tabs } from "@skeletonlabs/skeleton-react";
import { MembersList } from "@/components/organizations/ui/widget/Members";
import { InvitationsList } from "@/components/organizations/ui/widget/Invitations";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { useIsOwnerOrAdmin } from "@/components/organizations/api/hooks";
import InviteMembers from "./InviteMembers";

export default function Members() {
  const [group, setGroup] = useState("members");
  const members = useQuery(api.organizations.members.getOrganizationMembers);
  const invitations = useQuery(api.organizations.invitations.db.getInvitations);
  const isOwnerOrAdmin = useIsOwnerOrAdmin();

  return (
    <Tabs value={group} onValueChange={(e) => setGroup(e.value!)}>
      <Tabs.List>
        <Tabs.Control value="members">
          Members {members && `(${members.length})`}
        </Tabs.Control>
        {isOwnerOrAdmin && (
          <Tabs.Control value="invitations">
            Invitations {invitations && `(${invitations.length})`}
          </Tabs.Control>
        )}
      </Tabs.List>
      <Tabs.Content>
        <Tabs.Panel value="members">
          <InviteMembers />
          <MembersList />
        </Tabs.Panel>
        {isOwnerOrAdmin && (
          <Tabs.Panel value="invitations">
            <InvitationsList />
          </Tabs.Panel>
        )}
      </Tabs.Content>
    </Tabs>
  );
}

// svelte/src/lib/organizations/ui/MembersAndInvitations.svelte
<script lang="ts">
	// Components
	import { Tabs } from '@skeletonlabs/skeleton-svelte';
	import Members from '$lib/organizations/ui/Members.svelte';
	import Invitations from '$lib/organizations/ui/Invitations.svelte';
	import InviteMembers from '$lib/organizations/ui/InviteMembers.svelte';

	// API
	import { useQuery } from 'convex-svelte';
	import { api } from '$convex/_generated/api';
	import { isOwnerOrAdmin } from '$lib/organizations/api/roles.svelte';

	// Convex queries
	const membersResponse = useQuery(api.organizations.members.getOrganizationMembers, {});
	const invitationsResponse = useQuery(api.organizations.invitations.db.getInvitations, {});

	// Derived data
	const members = $derived(membersResponse.data);
	const invitations = $derived(invitationsResponse.data);

	let currentTab: string = $state('members');
</script>

<Tabs value={currentTab} onValueChange={(e) => (currentTab = e.value)}>
	{#snippet list()}
		<Tabs.Control value="members">Members {members && `(${members.length})`}</Tabs.Control>
		{#if isOwnerOrAdmin}
			<Tabs.Control value="invitations">
				Invitations {invitations && `(${invitations.length})`}
			</Tabs.Control>
		{/if}
	{/snippet}

	{#snippet content()}
		<Tabs.Panel value="members">
			<div class="mt-4">
				<InviteMembers />
				<Members />
			</div>
		</Tabs.Panel>

		{#if isOwnerOrAdmin}
			<Tabs.Panel value="invitations">
				<div class="mt-4">
					<Invitations />
				</div>
			</Tabs.Panel>
		{/if}
	{/snippet}
</Tabs>
