// nextjs/src/components/organizations/ui/widget/OrganizationProfile.tsx
import { useState } from "react";
import { Tabs } from "@skeletonlabs/skeleton-react";

// Components
import OrganizationInfo from "@/components/organizations/ui/widget/OrganizationInfo";
import DeleteOrganization from "@/components/organizations/ui/widget/DeleteOrganization";
import Members from "@/components/organizations/ui/widget/MembersAndInvitations";

// API
import { useIsOwnerOrAdmin } from "@/components/organizations/api/hooks";

interface OrganizationProfileProps {
  /**
   * Optional callback that will be called when an organization is successfully deleted
   */
  onSuccessfulDelete?: () => void;
}

export default function OrganizationProfile({
  onSuccessfulDelete,
}: OrganizationProfileProps) {
  const isOwnerOrAdmin = useIsOwnerOrAdmin();
  const [group, setGroup] = useState("general");
  return (
    <Tabs
      value={group}
      onValueChange={(e) => setGroup(e.value)}
      base="flex flex-row w-192 h-160"
    >
      <Tabs.List base="flex flex-col pr-2 w-30">
        <h1>Organization</h1>
        <h4>Manage your organization.</h4>
        <Tabs.Control
          value="general"
          base="border-r-1 border-transparent"
          stateActive="border-r-surface-950-50 opacity-100"
        >
          General
        </Tabs.Control>
        {isOwnerOrAdmin && (
          <>
            <Tabs.Control
              value="members"
              base="border-r-1 border-transparent"
              stateActive="border-r-surface-950-50 opacity-100"
            >
              Members
            </Tabs.Control>
            <Tabs.Control
              value="billing"
              base="border-r-1 border-transparent"
              stateActive="border-r-surface-950-50 opacity-100"
            >
              Billing
            </Tabs.Control>
          </>
        )}
      </Tabs.List>
      <Tabs.Content base="flex flex-col">
        <Tabs.Panel value="general">
          <OrganizationInfo />
          <DeleteOrganization onSuccessfulDelete={onSuccessfulDelete} />
          {/* <LeaveOrganization bind:user={user!} /> */}
        </Tabs.Panel>
        {isOwnerOrAdmin && (
          <>
            <Tabs.Panel value="members">
              <Members />
            </Tabs.Panel>
            <Tabs.Panel value="billing">Billing Panel</Tabs.Panel>
          </>
        )}
      </Tabs.Content>
    </Tabs>
  );
}

// svelte/src/lib/organizations/ui/OrganizationProfile.svelte
<script lang="ts">
	// Components
	import { Tabs } from '@skeletonlabs/skeleton-svelte';
	import OrganizationInfo from '$lib/organizations/ui/OrganizationInfo.svelte';
	import DeleteOrganization from '$lib/organizations/ui/DeleteOrganization.svelte';
	import MembersAndInvitations from '$lib/organizations/ui/MembersAndInvitations.svelte';
	import LeaveOrganization from '$lib/organizations/ui/LeaveOrganization.svelte';

	// API
	import { isOwnerOrAdmin } from '$lib/organizations/api/roles.svelte';

	// Types
	type OrganizationProfileProps = {
		/**
		 * Optional callback that will be called when an organization is successfully deleted
		 */
		onSuccessfulDelete?: (() => void) | undefined;
	};

	const { onSuccessfulDelete }: OrganizationProfileProps = $props();

	// State
	let currentTab: string = $state('general');
</script>

<Tabs
	value={currentTab}
	onValueChange={(e) => (currentTab = e.value)}
	base="flex flex-row w-192 h-160"
	listBase="flex flex-col pr-2 w-30"
	contentBase="flex flex-col"
>
	{#snippet list()}
		<h1>Organization</h1>
		<h4>Manage your organization.</h4>
		<Tabs.Control
			value="general"
			base="border-r-1 border-transparent"
			stateActive="border-r-surface-950-50 opacity-100"
		>
			General
		</Tabs.Control>
		{#if isOwnerOrAdmin}
			<Tabs.Control
				value="members"
				base="border-r-1 border-transparent"
				stateActive="border-r-surface-950-50 opacity-100"
			>
				Members
			</Tabs.Control>
			<Tabs.Control
				value="billing"
				base="border-r-1 border-transparent"
				stateActive="border-r-surface-950-50 opacity-100"
			>
				Billing
			</Tabs.Control>
		{/if}
	{/snippet}

	{#snippet content()}
		<Tabs.Panel value="general">
			<OrganizationInfo />
			<DeleteOrganization {onSuccessfulDelete} />
			<LeaveOrganization />
		</Tabs.Panel>
		{#if isOwnerOrAdmin}
			<Tabs.Panel value="members">
				<MembersAndInvitations />
			</Tabs.Panel>
			<Tabs.Panel value="billing">Billing Panel</Tabs.Panel>
		{/if}
	{/snippet}
</Tabs>
