// nextjs/src/components/organizations/ui/OrganizationProfileHost.tsx
'use client';

import { useEffect, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';

import * as Dialog from '@/components/primitives/ui/dialog';
import OrganizationProfile from '@/components/organizations/ui/OrganizationProfile';
import { DIALOG_KEY } from '@/components/organizations/utils/organization.constants';
import {
	isEditableElement,
	scheduleScrollIntoView
} from '@/components/primitives/utils/focusScroll';

export default function OrganizationProfileHost() {
	const router = useRouter();
	const pathname = usePathname();
	const searchParams = useSearchParams();
	const shouldBeOpen = searchParams.get('dialog') === DIALOG_KEY;
	const [open, setOpen] = useState(false);
	const [suppressTransition, setSuppressTransition] = useState(false);
	const [suppressDialogRender, setSuppressDialogRender] = useState(false);
	const [isIOS, setIsIOS] = useState(false);

	useEffect(() => {
		const ua = navigator.userAgent;
		setIsIOS(
			/iPhone|iPad|iPod/.test(ua) || (ua.includes('Macintosh') && navigator.maxTouchPoints > 1)
		);
	}, []);

	useEffect(() => setOpen(shouldBeOpen), [shouldBeOpen]);

	useEffect(() => {
		if (!isIOS) return;
		const onPopState = () => {
			setSuppressTransition(true);
			setSuppressDialogRender(true);
			window.setTimeout(() => {
				setSuppressTransition(false);
				setSuppressDialogRender(false);
			}, 450);
		};
		window.addEventListener('popstate', onPopState);
		return () => window.removeEventListener('popstate', onPopState);
	}, [isIOS]);

	function closeProfileModal() {
		const params = new URLSearchParams(searchParams.toString());
		if (params.get('dialog') === DIALOG_KEY) {
			params.delete('dialog');
			params.delete('tab');
			const query = params.toString();
			router.replace(`${pathname}${query ? `?${query}` : ''}`, { scroll: false });
		}
		setOpen(false);
	}

	if (suppressDialogRender) return null;

	return (
		<Dialog.Root
			open={open}
			onOpenChange={(nextOpen) => {
				if (!nextOpen) closeProfileModal();
				else setOpen(true);
			}}
		>
			<Dialog.Content
				className={`md:rounded-container top-0 left-0 h-full max-h-[100dvh] w-full max-w-full translate-x-0 translate-y-0 rounded-none p-0 md:top-1/2 md:left-1/2 md:h-[70vh] md:w-2xl md:-translate-x-1/2 md:-translate-y-1/2 lg:w-4xl ${suppressTransition ? 'animate-none transition-none duration-0 data-[state=closed]:duration-0 data-[state=open]:duration-0' : ''}`}
			>
				<div
					className="h-full w-full overflow-auto overscroll-contain"
					onFocus={(event) => {
						const el = event.target as HTMLElement | null;
						if (!el || isIOS || !isEditableElement(el)) return;
						scheduleScrollIntoView(el);
					}}
				>
					<OrganizationProfile open={open} onSuccessfulDelete={() => setOpen(false)} />
				</div>
				<Dialog.CloseX />
			</Dialog.Content>
		</Dialog.Root>
	);
}

// svelte/src/lib/organizations/ui/OrganizationProfileHost.svelte
<script lang="ts">
	// Svelte
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';

	// Primitives
	import * as Dialog from '$lib/primitives/ui/dialog';
	// Components
	import OrganizationProfile from '$lib/organizations/ui/OrganizationProfile.svelte';

	// Constants
	import { DIALOG_KEY } from '$lib/organizations/utils/organization.constants';

	// Types
	import type { Pathname } from '$app/types';
	import type {
		GetActiveOrganizationType,
		GetActiveUserType,
		ListInvitationsType,
		Role
	} from '$lib/types';

	type OrganizationProfileHostProps = {
		initialData?: {
			activeUser?: GetActiveUserType;
			activeOrganization?: GetActiveOrganizationType;
			invitationList?: ListInvitationsType;
			role?: Role;
		};
	};

	let { initialData }: OrganizationProfileHostProps = $props();

	// Local dialog state (formerly from singleton)
	let orgProfile = $state({
		open: false,
		suppressTransition: false
	});

	// iOS / gesture guards
	let isIOS = $state(false);
	let backSwipeGuard = $state(false);
	let guardTimer: ReturnType<typeof setTimeout> | null = null;
	let prevShouldBeOpen = false;
	let suppressDialogRender = $state(false);

	function closeOrganizationProfile(): void {
		orgProfile.open = false;
	}

	onMount(() => {
		// Detect iOS/iPadOS (including iPadOS 13+ which reports as Macintosh)
		const ua = navigator.userAgent;
		isIOS =
			/iPhone|iPad|iPod/.test(ua) || (ua.includes('Macintosh') && navigator.maxTouchPoints > 1);

		// Hydrate once from the URL so deep-links open at load
		const shouldBeOpen = page.url.searchParams.get('dialog') === DIALOG_KEY;
		orgProfile.open = shouldBeOpen;
		prevShouldBeOpen = shouldBeOpen;

		const onPopState = () => {
			if (!isIOS) return;
			const url = new URL(window.location.href);
			const shouldBeOpenNow = url.searchParams.get('dialog') === DIALOG_KEY;
			const closingCandidate = prevShouldBeOpen && !shouldBeOpenNow;
			if (closingCandidate) {
				backSwipeGuard = true;
				if (guardTimer) clearTimeout(guardTimer);
				guardTimer = setTimeout(() => {
					backSwipeGuard = false;
					guardTimer = null;
				}, 650);
			}
		};
		window.addEventListener('popstate', onPopState);
		return () => window.removeEventListener('popstate', onPopState);
	});

	// URL → state sync
	$effect(() => {
		const shouldBeOpen = page.url.searchParams.get('dialog') === DIALOG_KEY;
		const closingCandidate = prevShouldBeOpen && !shouldBeOpen;

		if (isIOS && closingCandidate && !backSwipeGuard) {
			backSwipeGuard = true;
			if (guardTimer) clearTimeout(guardTimer);
			guardTimer = setTimeout(() => {
				backSwipeGuard = false;
				guardTimer = null;
			}, 650);
		}

		const closingFromUrl = closingCandidate && backSwipeGuard;

		suppressDialogRender = !!closingFromUrl;
		orgProfile.open = closingFromUrl ? false : shouldBeOpen;
		prevShouldBeOpen = shouldBeOpen;
	});

	// Transition guard
	$effect(() => {
		if (backSwipeGuard) {
			orgProfile.suppressTransition = true;
		} else if (orgProfile.suppressTransition) {
			setTimeout(() => (orgProfile.suppressTransition = false), 100);
		}
	});

	function closeProfileModal() {
		const hasDialog = page.url.searchParams.get('dialog') === DIALOG_KEY;
		if (hasDialog) {
			const url = new URL(page.url);
			url.searchParams.delete('dialog');
			url.searchParams.delete('tab');
			void goto(resolve(`${url.pathname}${url.search}${url.hash}` as Pathname), {
				replaceState: true,
				noScroll: true,
				keepFocus: true
			});
		}
		orgProfile.open = false;
	}
</script>

{#if !suppressDialogRender}
	<Dialog.Root
		bind:open={orgProfile.open}
		onOpenChange={(status) => {
			if (!status.open) closeProfileModal();
		}}
	>
		<Dialog.Content
			class={`md:rounded-container top-0 left-0 h-full max-h-[100dvh] w-full max-w-full translate-x-0 translate-y-0 rounded-none p-0 md:top-1/2 md:left-1/2 md:h-[70vh] md:w-2xl md:-translate-x-1/2 md:-translate-y-1/2 lg:w-4xl ${orgProfile.suppressTransition ? 'animate-none transition-none duration-0 data-[state=closed]:duration-0 data-[state=open]:duration-0' : ''}`}
		>
			<div
				class="h-full w-full overflow-auto overscroll-contain"
				onfocusin={(e) => {
					const el = e.target as HTMLElement | null;
					if (!el) return;
					if (isIOS) return;

					const tag = el.tagName.toLowerCase();
					const isEditableTag = tag === 'input' || tag === 'textarea' || tag === 'select';
					const isContentEditable =
						el.isContentEditable || el.getAttribute('contenteditable') === 'true';
					const role = el.getAttribute('role');
					const isTextboxLike = role === 'textbox' || role === 'combobox' || role === 'searchbox';
					const isButtonLike =
						tag === 'button' || tag === 'a' || el.closest('[data-part="trigger"]');

					if ((isEditableTag || isContentEditable || isTextboxLike) && !isButtonLike) {
						el.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
					}
				}}
			>
				<OrganizationProfile
					open={orgProfile.open}
					onSuccessfulDelete={closeOrganizationProfile}
					{initialData}
				/>
			</div>
			<Dialog.CloseX />
		</Dialog.Content>
	</Dialog.Root>
{/if}
