// svelte/src/lib/organization/ui/widget/DeleteOrganization.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Modal } from '@skeletonlabs/skeleton-svelte';

	import { callForm } from '$lib/primitives/api/callForm';

	import type { User } from '$lib/db/schema/types/custom';

	interface Props {
		user: User;
	}

	let { user = $bindable() }: Props = $props();
	let open = $state(false);
	let error = $state('');

	let isOwner = $derived(user.roles?.includes('role_organization_owner'));

	async function handleConfirm() {
		try {
			await callForm({
				url: '/api/org?/deleteOrganization',
				data: { organizationId: user.activeOrganization!.id }
			});
			open = false;
			goto('/', { invalidateAll: true });
		} catch (err) {
			if (err instanceof Error) {
				error = err.message;
			} else {
				error = 'Unknown error. Please try again. If it persists, contact support.';
			}
		}
	}

	function handleCancel() {
		open = false;
	}
</script>

{#if isOwner}
	<Modal
		{open}
		onOpenChange={(e) => (open = e.open)}
		triggerBase="btn text-error-500 hover:preset-tonal-error-500"
		contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-(--breakpoint-sm)"
		backdropClasses="backdrop-blur-xs"
	>
		{#snippet trigger()}
			Delete organization
		{/snippet}
		{#snippet content()}
			<header class="flex justify-between">
				<h2 class="h2">Delete organization</h2>
			</header>
			<article>
				<p class="opacity-60">
					Are you sure you want to delete the organization {user.activeOrganization!.name}? All
					organization data will be permanently deleted.
				</p>
			</article>
			<footer class="flex justify-end gap-4">
				<button type="button" class="btn preset-tonal" onclick={handleCancel}> Cancel </button>
				<button type="button" class="btn preset-filled-error-500" onclick={handleConfirm}>
					Confirm
				</button>
			</footer>
			{#if error}
				<p class="text-error-600-400">{error}</p>
			{/if}
		{/snippet}
	</Modal>
{/if}

// nextjs/src/components/organizations/ui/widget/DeleteOrganization.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import {
  Modal,
  ModalTrigger,
  ModalContent,
  ModalHeading,
  ModalClose,
} from "@/components/primitives/ui/Modal";

import { useIsOwner } from "@/components/organizations/api/hooks";

/**
 * Component for deleting an organization
 * Only available to organization owners
 */
export default function DeleteOrganization() {
  const [open, setOpen] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  const router = useRouter();
  const activeOrganization = useQuery(api.organizations.getActiveOrganization);
  const isOwner = useIsOwner();

  const deleteOrganization = useMutation(api.organizations.deleteOrganization);

  if (!activeOrganization) {
    return null;
  }

  const handleConfirm = async (): Promise<void> => {
    try {
      await deleteOrganization({ organizationId: activeOrganization._id });
      setOpen(false);
      // Navigate to home and force a refresh
      router.push("/");
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError(
          "Unknown error. Please try again. If it persists, contact support."
        );
      }
    }
  };

  const handleCancel = (): void => {
    setOpen(false);
  };

  // If user is not an owner, don't render anything
  if (!isOwner) {
    return null;
  }

  return (
    <Modal open={open} onOpenChange={(open) => setOpen(open)}>
      <ModalTrigger className="btn text-error-500 hover:preset-tonal-error-500">
        Delete organization
      </ModalTrigger>

      <ModalContent>
        <ModalClose />
        <ModalHeading className="h2">Delete organization</ModalHeading>

        <article>
          <p className="opacity-60">
            Are you sure you want to delete the organization{" "}
            {activeOrganization.name}? All organization data will be permanently
            deleted.
          </p>
        </article>

        <footer className="flex justify-end gap-4 mt-4">
          <button
            type="button"
            className="btn preset-tonal"
            onClick={handleCancel}
          >
            Cancel
          </button>
          <button
            type="button"
            className="btn preset-filled-error-500"
            onClick={handleConfirm}
          >
            Confirm
          </button>
        </footer>

        {error && <p className="text-error-600-400 mt-2">{error}</p>}
      </ModalContent>
    </Modal>
  );
}
