// src/lib/organization/ui/widget/OrganizationProfile.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { Tabs } from '@skeletonlabs/skeleton-svelte';

	import ProfileInfo from './ProfileInfo.svelte';
	import DeleteOrganization from './DeleteOrganization.svelte';
	import LeaveOrganization from './LeaveOrganization.svelte';
	import Members from './Members.svelte';

	import type { User } from '$lib/db/schema/types/custom';

	let derivedUser: User | null = $derived(page.data.user ? JSON.parse(page.data.user) : null);

	let user = $state(page.data.user ? JSON.parse(page.data.user) : null);

	$effect(() => {
		user = derivedUser;
	});

	let group = $state('general');
</script>

{#if user.activeOrganization}
	<Tabs
		bind:value={group}
		base="flex flex-row w-192 h-160"
		listBase="flex flex-col pr-2 w-30"
		contentBase="flex flex-col"
	>
		{#snippet list()}
			<h1>Organization</h1>
			<h4>Manage your organization.</h4>
			<Tabs.Control
				value="general"
				base="border-r-1 border-transparent"
				stateActive="border-r-surface-950-50 opacity-100">General</Tabs.Control
			>
			<Tabs.Control
				value="members"
				base="border-r-1 border-transparent"
				stateActive="border-r-surface-950-50 opacity-100">Members</Tabs.Control
			>
			<Tabs.Control
				value="billing"
				base="border-r-1 border-transparent"
				stateActive="border-r-surface-950-50 opacity-100">Billing</Tabs.Control
			>
		{/snippet}
		{#snippet content()}
			<Tabs.Panel value="general">
				<ProfileInfo bind:user={user!} />
				<DeleteOrganization bind:user={user!} />
				<LeaveOrganization bind:user={user!} />
			</Tabs.Panel>
			<Tabs.Panel value="members">
				<Members bind:user={user!} />
			</Tabs.Panel>
			<Tabs.Panel value="billing">Billing Panel</Tabs.Panel>
		{/snippet}
	</Tabs>
{/if}

// nextjs/src/components/organizations/ui/widget/OrganizationProfile.tsx
import { useState } from "react";
import { Tabs } from "@skeletonlabs/skeleton-react";

// Components
import OrganizationInfo from "@/components/organizations/ui/widget/OrganizationInfo";

// API
import { useIsOwnerOrAdmin } from "@/components/organizations/api/hooks";

export default function OrganizationProfile() {
  const isOwnerOrAdmin = useIsOwnerOrAdmin();
  const [group, setGroup] = useState("general");
  return (
    <Tabs
      value={group}
      onValueChange={(e) => setGroup(e.value)}
      base="flex flex-row w-192 h-160"
    >
      <Tabs.List base="flex flex-col pr-2 w-30">
        <h1>Organization</h1>
        <h4>Manage your organization.</h4>
        <Tabs.Control
          value="general"
          base="border-r-1 border-transparent"
          stateActive="border-r-surface-950-50 opacity-100"
        >
          General
        </Tabs.Control>
        {isOwnerOrAdmin && (
          <>
            <Tabs.Control
              value="members"
              base="border-r-1 border-transparent"
              stateActive="border-r-surface-950-50 opacity-100"
            >
              Members
            </Tabs.Control>
            <Tabs.Control
              value="billing"
              base="border-r-1 border-transparent"
              stateActive="border-r-surface-950-50 opacity-100"
            >
              Billing
            </Tabs.Control>
          </>
        )}
      </Tabs.List>
      <Tabs.Content base="flex flex-col">
        <Tabs.Panel value="general">
          <OrganizationInfo />
          {/* <DeleteOrganization bind:user={user!} />
				<LeaveOrganization bind:user={user!} /> */}
        </Tabs.Panel>
        {isOwnerOrAdmin && (
          <>
            <Tabs.Panel value="members">
              {/* <Members bind:user={user!} /> */}
            </Tabs.Panel>
            <Tabs.Panel value="billing">Billing Panel</Tabs.Panel>
          </>
        )}
      </Tabs.Content>
    </Tabs>
  );
}
