// svelte/src/lib/organizations/ui/OrganizationSwitcher.svelte
<script lang="ts">
	// Navigation
	import { goto } from '$app/navigation';

	// Components
	import { Avatar, Popover, Modal } from '@skeletonlabs/skeleton-svelte';
	import { ChevronsUpDown, Plus, Settings, X } from 'lucide-svelte';
	import CreateOrganization from '$lib/organizations/ui/CreateOrganization.svelte';
	import OrganizationProfile from '$lib/organizations/ui/OrganizationProfile.svelte';
	import LeaveOrganization from '$lib/organizations/ui/LeaveOrganization.svelte';

	// API
	import { useQuery, useConvexClient } from 'convex-svelte';
	import { useAuth } from '@convex-dev/auth/sveltekit';
	import { api } from '$convex/_generated/api';
	const client = useConvexClient();

	// Types
	import type { Id } from '$convex/_generated/dataModel';
	import type { ComponentProps } from 'svelte';
	type PopoverProps = ComponentProps<typeof Popover>;
	type PlacementType = NonNullable<PopoverProps['positioning']>['placement'];
	import type { FunctionReturnType } from 'convex/server';
	type ActiveOrganizationResponse = FunctionReturnType<
		typeof api.organizations.getActiveOrganization
	>;
	type UserOrganizationsResponse = FunctionReturnType<
		typeof api.organizations.getUserOrganizations
	>;

	// Props
	const {
		popoverPlacement = 'bottom-end',
		initialData
	}: {
		popoverPlacement?: PlacementType;
		initialData?: {
			userOrganizations: UserOrganizationsResponse;
			activeOrganization: ActiveOrganizationResponse;
		};
	} = $props();

	// Authentication state
	const isLoading = $derived(useAuth().isLoading);
	const isAuthenticated = $derived(useAuth().isAuthenticated);

	// Queries
	const organizationsResponse = useQuery(
		api.organizations.getUserOrganizations,
		{},
		{ initialData: initialData?.userOrganizations }
	);
	const activeOrganizationResponse = useQuery(
		api.organizations.getActiveOrganization,
		{},
		{ initialData: initialData?.activeOrganization }
	);

	// Derived state
	const organizations = $derived(organizationsResponse.data);
	const activeOrganization = $derived(activeOrganizationResponse.data);

	// Component state
	let openSwitcher: boolean = $state(false);
	let openCreateOrganization: boolean = $state(false);
	let openOrganizationProfile: boolean = $state(false);

	// Handler functions
	function closeSwitcher(): void {
		openSwitcher = false;
	}

	function closeCreateOrganization(): void {
		openCreateOrganization = false;
	}

	function closeOrganizationProfile(): void {
		openOrganizationProfile = false;
	}

	/**
	 * Updates the active organization
	 */
	async function updateActiveOrg(organizationId: Id<'organizations'>): Promise<void> {
		try {
			await client.mutation(api.organizations.setActiveOrganization, { organizationId });

			// Close popover and refresh
			closeSwitcher();
			goto(window.location.href, { replaceState: true }); // refresh page
		} catch (err) {
			console.error(err);
		}
	}

	function openCreateOrgModal(): void {
		openCreateOrganization = true;
		closeSwitcher();
	}

	function openProfileModal(): void {
		openOrganizationProfile = true;
		closeSwitcher();
	}
</script>

<!-- Not authenticated - don't show anything -->
{#if !isAuthenticated}
	<!-- Return null by not rendering anything -->

	<!-- Loading state -->
{:else if isLoading || !organizations}
	<div class="placeholder h-8 w-40 animate-pulse"></div>

	<!-- No organizations - just show the create button -->
{:else if organizations.length === 0}
	<Modal
		open={openCreateOrganization}
		onOpenChange={(e) => (openCreateOrganization = e.open)}
		triggerBase="btn variant-soft flex items-center gap-2"
		contentBase="card bg-surface-100-900 relative max-w-screen-sm space-y-4 p-4 shadow-xl"
	>
		{#snippet trigger()}
			<Plus class="size-4" />
			<span>Create Organization</span>
		{/snippet}

		{#snippet content()}
			<CreateOrganization onSuccessfulCreate={closeCreateOrganization} />
			<button
				class="btn-icon variant-ghost absolute top-2 right-2"
				onclick={closeCreateOrganization}
			>
				<X class="size-4" />
			</button>
		{/snippet}
	</Modal>

	<!-- Has organizations - show the switcher -->
{:else}
	<Popover
		open={openSwitcher}
		onOpenChange={(e) => (openSwitcher = e.open)}
		positioning={{ placement: popoverPlacement }}
		triggerBase="flex items-center gap-2"
		contentBase="floating card bg-surface-200-800 max-w-100 p-4"
	>
		{#snippet trigger()}
			<Avatar
				src={activeOrganization?.logo || ''}
				name={activeOrganization?.name || ''}
				size="size-6"
			/>
			<span class="text-surface-700-300 text-base font-semibold">
				{activeOrganization?.name}
			</span>
			<ChevronsUpDown class="size-3" />
		{/snippet}

		{#snippet content()}
			<ul role="list" class="space-y-1">
				<li>
					<div
						class="rounded-base text-surface-700-300 flex items-center gap-x-3 p-2 text-sm font-semibold"
					>
						<Avatar
							src={activeOrganization?.logo || ''}
							name={activeOrganization?.name || ''}
							size="size-6"
						/>
						<span class="text-surface-700-300 text-base font-semibold">
							{activeOrganization?.name}
						</span>
						{#if activeOrganization?.role === 'role_organization_owner' || activeOrganization?.role === 'role_organization_admin'}
							<button onclick={openProfileModal} class="btn variant-outline-surface flex gap-2">
								<Settings class="size-4" />
								<span class="text-xs">Manage</span>
							</button>
						{:else if activeOrganization}
							<LeaveOrganization />
						{/if}
					</div>
				</li>

				{#each organizations.filter((org) => org && org._id !== activeOrganization?._id) as org}
					{#if org}
						<li>
							<button
								onclick={() => updateActiveOrg(org._id)}
								class="group rounded-base text-surface-700-300 hover:text-primary-600-400 hover:bg-surface-100-900 flex w-full gap-x-3 p-2 text-sm font-semibold"
							>
								<Avatar src={org.logo || ''} name={org.name} size="size-6" />
								<span class="text-surface-700-300 text-base font-semibold">
									{org.name}
								</span>
							</button>
						</li>
					{/if}
				{/each}

				<li>
					<button
						onclick={openCreateOrgModal}
						class="btn variant-soft mt-2 flex w-full items-center gap-2"
					>
						<Plus class="size-4" />
						<span>Create Organization</span>
					</button>
				</li>
			</ul>
		{/snippet}
	</Popover>

	<!-- Create Organization Modal -->
	<Modal
		open={openCreateOrganization}
		onOpenChange={(e) => (openCreateOrganization = e.open)}
		contentBase="card p-4 w-full max-w-md shadow-xl"
	>
		{#snippet content()}
			<div class="relative">
				<CreateOrganization onSuccessfulCreate={closeCreateOrganization} />
				<button
					class="btn-icon variant-ghost absolute top-2 right-2"
					onclick={closeCreateOrganization}
				>
					<X class="size-4" />
				</button>
			</div>
		{/snippet}
	</Modal>

	<!-- Organization Profile Modal -->
	<Modal
		open={openOrganizationProfile}
		onOpenChange={(e) => (openOrganizationProfile = e.open)}
		contentBase="card bg-surface-100-900 relative space-y-4 p-4 shadow-xl"
		backdropBase="bg-surface-50-950/75 fixed top-0 right-0 bottom-0 left-0 flex items-center justify-center p-4 backdrop-blur-sm"
	>
		{#snippet content()}
			<div class="relative">
				<OrganizationProfile onSuccessfulDelete={closeOrganizationProfile} />
				<button
					class="btn-icon variant-ghost absolute top-2 right-2"
					onclick={closeOrganizationProfile}
				>
					<X class="size-4" />
				</button>
			</div>
		{/snippet}
	</Modal>
{/if}

// nextjs/src/components/organizations/ui/widget/OrganizationSwitcher.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronsUpDown, Plus, Settings, X } from "lucide-react";
import { Avatar } from "@skeletonlabs/skeleton-react";

// Components
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/primitives/ui/Popover";
import {
  Modal,
  ModalContent,
  ModalClose,
  ModalTrigger,
} from "@/components/primitives/ui/Modal";
import CreateOrganization from "@/components/organizations/ui/widget/CreateOrganization";
import OrganizationProfile from "@/components/organizations/ui/widget/OrganizationProfile";

// API
import { useQuery, useMutation, useConvexAuth } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";

/**
 * Organization switcher component that allows switching between organizations,
 * creating new organizations, and accessing organization settings.
 * Only displayed when the user is authenticated.
 */
export default function OrganizationSwitcher() {
  const router = useRouter();
  const { isLoading, isAuthenticated } = useConvexAuth();

  // Queries and mutations
  const organizations = useQuery(api.organizations.getUserOrganizations);
  const activeOrganization = useQuery(api.organizations.getActiveOrganization);
  const setActiveOrg = useMutation(api.organizations.setActiveOrganization);

  // State
  const [openSwitcher, setOpenSwitcher] = useState<boolean>(false);
  const [openCreateOrganization, setOpenCreateOrganization] =
    useState<boolean>(false);
  const [openOrganizationProfile, setOpenOrganizationProfile] =
    useState<boolean>(false);

  /**
   * Updates the active organization
   */
  const updateActiveOrg = async (organizationId: Id<"organizations">) => {
    try {
      await setActiveOrg({ organizationId });

      // Close popover and refresh
      setOpenSwitcher(false);
      router.refresh();
    } catch (err) {
      console.error(err);
    }
  };

  /**
   * Temporary LeaveOrganization component (will be implemented separately)
   */
  const LeaveOrganization = ({
    organizationId,
  }: {
    organizationId: Id<"organizations">;
  }) => (
    <button
      onClick={() => console.log("Leave organization:", organizationId)}
      className="btn preset-outlined-error-500 flex gap-2"
    >
      <X size={16} />
      <span>Leave</span>
    </button>
  );

  // Not authenticated - don't show anything
  if (!isAuthenticated) {
    return null;
  }

  // Loading state
  if (isLoading || !organizations) {
    return <div className="animate-pulse h-8 w-40 placeholder"></div>;
  }

  // No organizations - just show the create button
  if (organizations.length === 0) {
    return (
      <Modal
        open={openCreateOrganization}
        onOpenChange={setOpenCreateOrganization}
      >
        <ModalTrigger className="btn preset-tonal flex items-center gap-2">
          <Plus size={16} />
          <span>Create Organization</span>
        </ModalTrigger>
        <ModalContent>
          <CreateOrganization
            onSuccessfulCreate={() => setOpenCreateOrganization(false)}
          />
          <ModalClose />
        </ModalContent>
      </Modal>
    );
  }

  // Has organizations - show the switcher
  return (
    <>
      <Popover
        open={openSwitcher}
        onOpenChange={setOpenSwitcher}
        placement="bottom-end"
      >
        <PopoverTrigger onClick={() => setOpenSwitcher(!openSwitcher)}>
          <div className="flex items-center gap-2">
            <Avatar
              src={activeOrganization?.logo || ""}
              name={activeOrganization?.name || ""}
              size="size-6"
            />
            <span className="text-surface-700-300 text-base font-semibold">
              {activeOrganization?.name}
            </span>
            <ChevronsUpDown size={12} />
          </div>
        </PopoverTrigger>

        <PopoverContent>
          <ul role="list" className="space-y-1">
            <li>
              <div className="rounded-base text-surface-700-300 flex items-center gap-x-3 p-4 text-sm/6 font-semibold">
                <Avatar
                  src={activeOrganization?.logo || ""}
                  name={activeOrganization?.name || ""}
                  size="size-6"
                />
                <span className="text-surface-700-300 text-base font-semibold">
                  {activeOrganization?.name}
                </span>
                {activeOrganization?.role === "role_organization_owner" ||
                activeOrganization?.role === "role_organization_admin" ? (
                  <button
                    onClick={() => {
                      setOpenOrganizationProfile(true);
                      setOpenSwitcher(false);
                    }}
                    className="btn preset-outlined-surface-500 flex gap-2"
                  >
                    <Settings size={16} />
                    <span>Manage</span>
                  </button>
                ) : (
                  activeOrganization && (
                    <LeaveOrganization
                      organizationId={activeOrganization._id}
                    />
                  )
                )}
              </div>
            </li>

            {organizations
              .filter((org) => org && org._id !== activeOrganization?._id)
              .map(
                (org) =>
                  org && (
                    <li key={org._id}>
                      <button
                        onClick={() => updateActiveOrg(org._id)}
                        className="group rounded-base text-surface-700-300 hover:text-primary-600-400 flex gap-x-3 p-4 text-sm/6 font-semibold hover:bg-surface-100-900 w-full"
                      >
                        <Avatar
                          src={org.logo || ""}
                          name={org.name}
                          size="size-6"
                        />
                        <span className="text-surface-700-300 text-base font-semibold">
                          {org.name}
                        </span>
                      </button>
                    </li>
                  )
              )}

            <li>
              <button
                onClick={() => {
                  setOpenCreateOrganization(true);
                  setOpenSwitcher(false);
                }}
                className="btn preset-tonal flex items-center gap-2 w-full"
              >
                <Plus size={16} />
                <span>Create Organization</span>
              </button>
            </li>
          </ul>
        </PopoverContent>
      </Popover>

      <Modal
        open={openCreateOrganization}
        onOpenChange={setOpenCreateOrganization}
      >
        <ModalContent>
          <CreateOrganization
            onSuccessfulCreate={() => setOpenCreateOrganization(false)}
          />
          <ModalClose />
        </ModalContent>
      </Modal>

      <Modal
        open={openOrganizationProfile}
        onOpenChange={setOpenOrganizationProfile}
      >
        <ModalContent>
          <OrganizationProfile
            onSuccessfulDelete={() => setOpenOrganizationProfile(false)}
          />
          <ModalClose />
        </ModalContent>
      </Modal>
    </>
  );
}
