// src/lib/auth/ui/widget/SignIn.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';

	import { callForm } from '$lib/primitives/api/callForm';
	import { signInWithPasskey, signUpWithPasskey } from '$lib/auth/api/passkey';
	import SocialProvider from '$lib/auth/social/provider.svelte';

	import type { VerifyEmailReturnData } from '$lib/user/api/types';
	import { Fingerprint } from 'lucide-svelte';

	let errorMessage = $state('');

	let email = $state('');
	let firstName = $state('');
	let lastName = $state('');
	let otp = $state('');

	let userExists: boolean | null = $state(null); // null means we haven't checked yet

	onMount(() => {
		const urlParams = new URLSearchParams(page.url.searchParams);
		const encodedErrorMessage = urlParams.get('error') || '';
		if (encodedErrorMessage) {
			errorMessage = decodeURIComponent(encodedErrorMessage);
			urlParams.delete('error');
			history.replaceState(null, '', '?' + urlParams.toString());
		}
	});

	$effect(() => {
		if (userExists) {
			signInWithPasskey();
		}
	});

	async function verifyEmailAndSendVerification(event: SubmitEvent) {
		event.preventDefault();
		try {
			const verificationResult = await callForm<VerifyEmailReturnData>({
				url: `/user-profile?/verifyEmailAndSendVerification`,
				data: { email }
			});

			if (!verificationResult.valid) {
				errorMessage = `Please use a valid email.`;
			} else {
				userExists = verificationResult.exists;
				errorMessage = ``;
			}

			console.log('verificationResult: ', verificationResult);
			console.log('userExists: ', userExists);
		} catch (err: any) {
			errorMessage = err?.message ?? 'Error verifying email.';
		}
	}

	async function handleSignInWithPasskey() {
		try {
			await signInWithPasskey();
		} catch (err) {
			if (err instanceof Error) {
				errorMessage = err.message;
			} else {
				errorMessage = 'An unknown error occurred.';
			}
		}
	}

	async function handleSignUpWithPasskey(event: SubmitEvent) {
		event.preventDefault();
		try {
			await signUpWithPasskey({ firstName, lastName, email, otp });
		} catch (error: any) {
			errorMessage = error.message || 'An error occurred during sign up.';
		}
	}
</script>

<div class="flex min-h-screen items-center justify-center">
	<div
		class="card border-surface-200-800 flex w-full max-w-md flex-col gap-6 border p-6 text-center"
	>
		<!-- Title -->
		<div id="auth_sign-in_title" class="flex flex-col gap-3">
			<h2 class="h3 text-center">Sign in</h2>
		</div>

		<!-- Sign-In -->
		<SocialProvider />

		<button
			class="btn preset-filled-surface-100-900 flex items-center gap-2"
			onclick={handleSignInWithPasskey}
		>
			<Fingerprint class="text-surface-950-50" />
			Continue with Passkey
		</button>

		<!-- Divider -->
		<div class="flex items-center">
			<hr class="hr" />
			<div class="text-surface-500 mx-4">OR</div>
			<hr class="hr" />
		</div>

		{#if userExists !== true}
			<div id="auth_sign-in_title" class="flex flex-col gap-3">
				<h2 class="h3 text-center">Create account</h2>
				<p class="text-surface-600-400 text-center">Get started for free</p>
			</div>
		{/if}

		<!-- If user existence not checked or if user doesn't exist yet, show email form -->
		{#if userExists === null}
			<form class="flex flex-col gap-3" onsubmit={verifyEmailAndSendVerification}>
				<input
					class="input"
					type="email"
					bind:value={email}
					placeholder="Enter your email"
					required
				/>
				<button class="btn preset-filled w-full" type="submit">Continue</button>
			</form>
		{/if}

		<!-- If user does not exist, show sign-up fields -->
		{#if userExists === false}
			<form class="flex flex-col gap-3" onsubmit={handleSignUpWithPasskey} autocomplete="off">
				<input class="input" type="text" bind:value={firstName} placeholder="First name" required />
				<input class="input" type="text" bind:value={lastName} placeholder="Last name" required />
				<input
					class="input"
					type="text"
					bind:value={otp}
					placeholder="One time password"
					required
				/>
				<!-- email is already known, but let's keep it for clarity -->
				<input
					class="input disabled:bg-surface-100-900"
					type="email"
					bind:value={email}
					placeholder="Email"
					disabled
					required
				/>

				<button class="btn preset-filled w-full" type="submit"> Create Passkey and Sign Up </button>
			</form>
		{/if}

		{#if userExists === true}
			<div class="flex flex-col gap-3">
				<p class="text-surface-600-400 text-center">
					An account for this email already exists. Sign in instead.
				</p>
			</div>
		{/if}

		{#if userExists === false}
			<p class="text-center text-xs">
				By continuing, you agree to our <a href="/terms" class="anchor">Terms of Service</a> and
				<a href="/privacy-policy" class="anchor">Privacy Policy</a>.
			</p>
		{/if}

		{#if errorMessage}
			<p class="text-error-500">{errorMessage}</p>
		{/if}
	</div>
</div>

// nextjs/src/components/auth/ui/SignIn.tsx
'use client';

// React
import { useState } from 'react';
// Nextjs
import { redirect, useSearchParams } from 'next/navigation';

// Primitives
import { toast } from 'sonner';

// Constants
import { AUTH_CONSTANTS } from '@/convex/auth.constants';
// API
import { useAction } from 'convex/react';
import { api } from '@/convex/_generated/api';
import { authClient } from '../lib/auth-client';

type AuthStep = 'email' | 'login' | 'register';

interface SignInProps {
	redirectTo?: string;
	onSignIn?: () => void;
}

export default function SignIn({ redirectTo: redirectParam, onSignIn }: SignInProps = {}) {
	const checkEmailAvailabilityAndValidity = useAction(
		api.users.actions.checkEmailAvailabilityAndValidity
	);
	const searchParams = useSearchParams();

	const [currentStep, setCurrentStep] = useState<AuthStep>('email');
	const [email, setEmail] = useState('');
	const [submitting, setSubmitting] = useState(false);
	const [verifyingEmail, setVerifyingEmail] = useState(false);

	/**
	 * Gets the redirect URL based on parameters and current page
	 */
	const getRedirectUrl = (): string => {
		return (
			redirectParam ??
			searchParams.get('redirectTo') ??
			(window.location.pathname.includes('/signin') ? '/' : window.location.pathname)
		);
	};

	/**
	 * Handles sign in with the specified provider
	 */
	const handleSocialSignIn = (): void => {
		authClient.signIn.social({ provider: 'github' }).then((result) => {
			if (result.data) {
				onSignIn?.();
				redirect(getRedirectUrl());
			} else {
				console.error('Social sign in error:', result.error);
				toast.error('Failed to sign in with GitHub. Please try again.');
			}
		});
	};

	/**
	 * Verifies if email exists and determines the appropriate flow
	 */
	const verifyEmail = async (emailValue: string): Promise<void> => {
		setVerifyingEmail(true);

		try {
			const data = await checkEmailAvailabilityAndValidity({
				email: emailValue
			});

			if (data.exists) {
				setCurrentStep('login');
			} else if (data.valid) {
				setCurrentStep('register');
			} else {
				toast.error('Invalid email. Please try again.');
			}
		} catch (error) {
			toast.error('Failed to verify email. Please try again.');

			console.error('Email verification error:', error);
		} finally {
			setVerifyingEmail(false);
		}
	};

	/**
	 * Handles email form submission
	 */
	const handleEmailSubmit = (event: React.FormEvent<HTMLFormElement>): void => {
		event.preventDefault();
		const formData = new FormData(event.currentTarget);
		const emailValue = formData.get('email') as string;

		if (emailValue) {
			setEmail(emailValue);
			void verifyEmail(emailValue);
		}
	};

	/**
	 * Handles authentication form submission (login or register)
	 */
	const handlePasswordSignIn = async (event: React.FormEvent<HTMLFormElement>): Promise<void> => {
		event.preventDefault();
		setSubmitting(true);

		const formData = new FormData(event.currentTarget);

		if (currentStep === 'login') {
			await authClient.signIn.email(
				{
					email,
					password: formData.get('password') as string
				},
				{
					onSuccess: () => {
						console.log('Sign in successful');
						toast.success('Signed in successfully!');
						onSignIn?.();
						redirect(getRedirectUrl());
					},
					onError: (ctx) => {
						console.error('Sign in error:', ctx.error);
						let errorMessage = 'Could not sign in. Please check your credentials.';

						if (ctx.error.message) {
							if (
								ctx.error.message.includes('Invalid password') ||
								ctx.error.message.includes('password')
							) {
								errorMessage = 'Invalid password. Please try again.';
							} else if (
								ctx.error.message.includes('not found') ||
								ctx.error.message.includes('email')
							) {
								errorMessage = 'No account found with this email.';
							} else {
								errorMessage = ctx.error.message;
							}
						}

						toast.error(errorMessage);
						setSubmitting(false);
					}
				}
			);
		} else if (currentStep === 'register') {
			await authClient.signUp.email(
				{
					email,
					password: formData.get('password') as string,
					name: formData.get('name') as string
				},
				{
					onSuccess: () => {
						console.log('Sign up successful');
						toast.success('Account created successfully!');
						onSignIn?.();
						redirect(getRedirectUrl());
					},
					onError: (ctx) => {
						console.error('Sign up error:', ctx.error);
						let errorMessage = 'Could not create account. Please try again.';

						if (ctx.error.message) {
							if (
								ctx.error.message.includes('already exists') ||
								ctx.error.message.includes('duplicate')
							) {
								errorMessage = 'An account with this email already exists.';
							} else if (ctx.error.message.includes('password')) {
								errorMessage = 'Password does not meet requirements.';
							} else {
								errorMessage = ctx.error.message;
							}
						}

						toast.error(errorMessage);
						setSubmitting(false);
					}
				}
			);
		}
	};

	/**
	 * Resets the flow back to email entry
	 */
	const resetFlow = (): void => {
		setCurrentStep('email');
		setEmail('');
	};

	const renderEmailStep = () => (
		<form className="flex flex-col gap-2" onSubmit={handleEmailSubmit}>
			<input
				className="input"
				type="email"
				name="email"
				placeholder="Enter your email"
				required
				disabled={verifyingEmail}
			/>
			<button className="btn preset-filled" type="submit" disabled={verifyingEmail}>
				{verifyingEmail ? 'Verifying...' : 'Continue'}
			</button>
		</form>
	);

	const renderLoginStep = () => (
		<form className="flex flex-col gap-2" onSubmit={handlePasswordSignIn}>
			<input className="input" type="email" name="email" value={email} disabled />
			<input
				className="input"
				type="password"
				name="password"
				placeholder="Enter your password"
				required
			/>
			<button className="btn preset-filled" type="submit" disabled={submitting}>
				{submitting ? 'Signing in...' : 'Sign in'}
			</button>
			<button type="button" className="anchor text-center text-sm" onClick={resetFlow}>
				Use a different email
			</button>
		</form>
	);

	const renderRegisterStep = () => (
		<form className="flex flex-col gap-2" onSubmit={handlePasswordSignIn}>
			<input className="input" type="email" name="email" value={email} disabled />
			<input className="input" type="text" name="name" placeholder="Enter your name" required />
			<input
				className="input"
				type="password"
				name="password"
				placeholder="Create a password"
				required
			/>
			<button className="btn preset-filled" type="submit" disabled={submitting}>
				{submitting ? 'Creating account...' : 'Create account'}
			</button>
			<button type="button" className="anchor text-center text-sm" onClick={resetFlow}>
				Use a different email
			</button>
		</form>
	);

	return (
		<div className="flex h-full w-full flex-col items-center justify-center">
			<div className="flex h-full w-full max-w-md flex-col p-8">
				<h5 className="h4 max-w-96 text-left leading-9 tracking-tighter">
					Build your app 10x faster <br /> with Skeleton Plus
				</h5>
				<p className="text-surface-600-400 mt-3 mb-10 max-w-96 text-left text-sm">
					Pre-built auth, UI kit, theme generator, and guides — everything you need to start fast.
				</p>
				<div className="flex h-full w-full flex-col gap-8">
					{AUTH_CONSTANTS.providers.github && (
						<button
							className="btn preset-filled hover:border-surface-600-400 w-full shadow-sm"
							onClick={handleSocialSignIn}
						>
							<svg
								aria-label="GitHub logo"
								width="20"
								height="20"
								xmlns="http://www.w3.org/2000/svg"
								viewBox="0 0 24 24"
							>
								<path
									fill="currentColor"
									d="M12,2A10,10 0 0,0 2,12C2,16.42 4.87,20.17 8.84,21.5C9.34,21.58 9.5,21.27 9.5,21C9.5,20.77 9.5,20.14 9.5,19.31C6.73,19.91 6.14,17.97 6.14,17.97C5.68,16.81 5.03,16.5 5.03,16.5C4.12,15.88 5.1,15.9 5.1,15.9C6.1,15.97 6.63,16.93 6.63,16.93C7.5,18.45 8.97,18 9.54,17.76C9.63,17.11 9.89,16.67 10.17,16.42C7.95,16.17 5.62,15.31 5.62,11.5C5.62,10.39 6,9.5 6.65,8.79C6.55,8.54 6.2,7.5 6.75,6.15C6.75,6.15 7.59,5.88 9.5,7.17C10.29,6.95 11.15,6.84 12,6.84C12.85,6.84 13.71,6.95 14.5,7.17C16.41,5.88 17.25,6.15 17.25,6.15C17.8,7.5 17.45,8.54 17.35,8.79C18,9.5 18.38,10.39 18.38,11.5C18.38,15.32 16.04,16.16 13.81,16.41C14.17,16.72 14.5,17.33 14.5,18.26C14.5,19.6 14.5,20.68 14.5,21C14.5,21.27 14.66,21.59 15.17,21.5C19.14,20.16 22,16.42 22,12A10,10 0 0,0 12,2Z"
								></path>
							</svg>
							Sign in with GitHub
						</button>
					)}

					{AUTH_CONSTANTS.providers.github && AUTH_CONSTANTS.providers.password && (
						<div className="relative flex items-center">
							<div className="border-surface-600-400 flex-1 border-t"></div>
							<span className="text-surface-600-400 px-4">OR</span>
							<div className="border-surface-600-400 flex-1 border-t"></div>
						</div>
					)}

					{/* Progressive Email Flow */}
					{AUTH_CONSTANTS.providers.password && (
						<>
							{currentStep === 'email' && renderEmailStep()}
							{currentStep === 'login' && renderLoginStep()}
							{currentStep === 'register' && renderRegisterStep()}
						</>
					)}
				</div>
				<div>
					<p className="text-surface-600-400 mt-10 text-xs">
						By continuing, you agree to our{' '}
						<a href={AUTH_CONSTANTS.terms} className="anchor text-surface-950-50">
							Terms
						</a>{' '}
						and{' '}
						<a href={AUTH_CONSTANTS.privacy} className="anchor text-surface-950-50">
							Privacy Policies
						</a>
					</p>
				</div>
			</div>
		</div>
	);
}
