// svelte/src/lib/auth/ui/SignOutButton.svelte
<script lang="ts">
	import { cn } from '$lib/primitives/utils';
	import { authClient } from '../api/auth-client';
	import { invalidateAll } from '$app/navigation';

	interface SignOutButtonProps {
		onSuccess?: () => void;
		onError?: () => void;
		class?: string;
	}

	const { onSuccess, onError, class: className }: SignOutButtonProps = $props();

	async function handleSignOut() {
		const result = await authClient.signOut();
		if (result.data?.success) {
			onSuccess?.();
			// Use invalidateAll() to refresh all data and trigger middleware re-execution
			invalidateAll();
		} else {
			onError?.();
		}
	}
</script>

<button
	class={cn(
		'btn preset-faded-surface-50-950 hover:bg-surface-200-800 h-10 justify-between gap-1 text-sm',
		className
	)}
	onclick={handleSignOut}
>
	Sign out
</button>

// nextjs/src/components/auth/ui/SignOutButton.tsx
import { cn } from '@/components/lib/utils';
import { authClient } from '../api/auth-client';
import { useRouter } from 'next/navigation';

export default function SignOutButton({
	onSuccess,
	onError,
	className
}: {
	onSuccess?: () => void;
	onError?: () => void;
	className?: string;
}) {
	const router = useRouter();
	return (
		<button
			className={cn(
				'btn preset-faded-surface-50-950 hover:bg-surface-200-800 h-10 justify-between gap-1 text-sm',
				className
			)}
			onClick={async () => {
				const result = await authClient.signOut();
				if (result.data?.success) {
					onSuccess?.();
					router.refresh();
				} else {
					onError?.();
				}
			}}
		>
			Sign out
		</button>
	);
}
