// nextjs/src/components/organizations/ui/Members.tsx
import { useState, useMemo } from 'react';

// API
import { useMutation, useQuery } from 'convex/react';
import { api } from '@/convex/_generated/api';

// Components
import {
	Dialog,
	DialogTrigger,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogClose,
	DialogFooter
} from '@/components/primitives/ui/dialog';
import { Avatar } from '@skeletonlabs/skeleton-react';
import { Shield, ShieldCheck, Search } from 'lucide-react';

// Types
import { Doc, Id } from '@/convex/_generated/dataModel';
type Role = Doc<'organizationMembers'>['role'];

// Hooks
import { useIsOwnerOrAdmin } from '@/components/organizations/api/hooks';

/**
 * Component that displays a list of organization members with role management functionality
 */
export function Members(): React.ReactNode {
	// State hooks
	const [errorMessage, setErrorMessage] = useState<string>('');
	const [successMessage, setSuccessMessage] = useState<string>('');
	const [selectedUserId, setSelectedUserId] = useState<Id<'users'> | null>(null);
	const [searchQuery, setSearchQuery] = useState<string>('');

	// Get current organization data
	const currentUser = useQuery(api.users.getUser);
	const currentOrganization = useQuery(api.organizations.getActiveOrganization);
	const isOwnerOrAdmin = useIsOwnerOrAdmin();

	// Get members data and mutations
	const members = useQuery(api.organizations.members.getOrganizationMembers);
	const updateMemberRole = useMutation(api.organizations.members.updateMemberRole);
	const removeMember = useMutation(api.organizations.members.removeMember);

	/**
	 * Filter and sort members based on search query and role
	 */
	const filteredMembers = useMemo(() => {
		if (!members) return [];

		return members
			.filter((member) => {
				if (!searchQuery) return true;

				const memberName = member.user.name;
				return memberName.toLowerCase().includes(searchQuery.toLowerCase());
			})
			.sort((a, b) => {
				// Sort by role (owner first, then admin, then member)
				const roleOrder: Record<Role, number> = {
					role_organization_owner: 0,
					role_organization_admin: 1,
					role_organization_member: 2
				};

				// Primary sort by role
				const roleDiff = roleOrder[a.role] - roleOrder[b.role];
				if (roleDiff !== 0) return roleDiff;

				// Secondary sort by name
				return a.user.name.localeCompare(b.user.name);
			});
	}, [members, searchQuery]);

	/**
	 * Handles updating a member's role
	 */
	const handleUpdateRole = async (userId: Id<'users'>, newRole: Role): Promise<void> => {
		if (newRole === 'role_organization_owner') return; // Cannot set someone as owner this way

		try {
			await updateMemberRole({
				userId,
				newRole
			});

			setErrorMessage('');
			setSuccessMessage('Role updated successfully!');
		} catch (err) {
			setSuccessMessage('');
			setErrorMessage(err instanceof Error ? err.message : 'Failed to update role');
			console.error(err);
		}
	};

	/**
	 * Handles removing a member from the organization
	 */
	const handleRemoveMember = async (): Promise<void> => {
		if (!selectedUserId) return;

		try {
			await removeMember({
				userId: selectedUserId
			});

			setErrorMessage('');
			setSuccessMessage('Member removed successfully!');
		} catch (err) {
			setSuccessMessage('');
			setErrorMessage(
				err instanceof Error
					? err.message
					: 'Unknown error. Please try again. If it persists, contact support.'
			);
		}
	};

	if (!members) {
		return <div>Loading members...</div>;
	}

	if (!currentOrganization || !currentUser) {
		return <div>Failed to load members</div>;
	}

	return (
		<div>
			{errorMessage && <p className="text-error-500">{errorMessage}</p>}
			{successMessage && <p className="text-success-500">{successMessage}</p>}

			<div className="mb-4 flex items-center gap-3">
				<div className="relative flex-1">
					<div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
						<Search className="text-surface-400-600 size-4" />
					</div>
					<input
						type="text"
						className="input w-full pl-10"
						placeholder="Search members..."
						value={searchQuery}
						onChange={(e) => setSearchQuery(e.target.value)}
					/>
				</div>
			</div>

			<table className="table caption-bottom">
				<thead>
					<tr className="border-surface-300-700 border-b">
						<th className="p-2 text-left">Name</th>
						<th className="p-2 text-left">Email</th>
						<th className="p-2 text-left">Role</th>
						{isOwnerOrAdmin && <th className="p-2 text-right">Actions</th>}
					</tr>
				</thead>
				<tbody>
					{filteredMembers.map((member) => (
						<tr key={member._id}>
							{/* Member Name */}
							<td>
								<div className="flex items-center space-x-4">
									<div className="avatar">
										<div className="size-12">
											{member.user.image ? (
												<Avatar src={member.user.image} name={member.user.name} size="size-12" />
											) : (
												<div className="bg-primary-100 text-primary-700 flex h-full w-full items-center justify-center rounded-full">
													{member.user.name?.charAt(0) || 'U'}
												</div>
											)}
										</div>
									</div>
									<span className="font-semibold">{member.user.name}</span>
								</div>
							</td>
							{/* Member Email */}
							<td>{member.user.email}</td>
							{/* Member Role */}
							<td>
								<div className="flex items-center">
									{isOwnerOrAdmin &&
									member.user._id !== currentUser._id &&
									member.role !== 'role_organization_owner' ? (
										<select
											value={member.role}
											onChange={(e) => handleUpdateRole(member.user._id, e.target.value as Role)}
											className="select"
										>
											<option value="role_organization_admin">Admin</option>
											<option value="role_organization_member">Member</option>
										</select>
									) : member.role === 'role_organization_owner' ? (
										<>
											<ShieldCheck className="text-primary-500 mr-1 size-4" />
											<span className="font-medium">Owner</span>
										</>
									) : member.role === 'role_organization_admin' ? (
										<>
											<Shield className="text-primary-400 mr-1 size-4" />
											<span className="font-medium">Admin</span>
										</>
									) : (
										<span>Member</span>
									)}
								</div>
							</td>
							{/* Member Actions */}
							<td>
								<div className="flex justify-end space-x-2">
									{isOwnerOrAdmin &&
										member.user._id !== currentUser._id &&
										member.role !== 'role_organization_owner' && (
											<Dialog>
												<DialogTrigger
													className="btn text-error-500 hover:preset-tonal-error-500"
													onClick={() => setSelectedUserId(member.user._id)}
												>
													Remove
												</DialogTrigger>
												<DialogContent className="card bg-surface-100-900 max-w-(--breakpoint-sm) space-y-4 p-4 shadow-xl">
													<DialogClose />
													<DialogHeader>
														<DialogTitle className="h2">Remove member</DialogTitle>
													</DialogHeader>
													<article>
														<p className="opacity-60">
															Are you sure you want to remove the member {member.user.name}?
														</p>
													</article>
													<DialogFooter>
														<DialogClose className="btn preset-tonal">Cancel</DialogClose>
														<button
															type="button"
															className="btn preset-filled-error-400-600"
															onClick={handleRemoveMember}
														>
															Confirm
														</button>
													</DialogFooter>
													{errorMessage && <p className="text-error-600-400">{errorMessage}</p>}
												</DialogContent>
											</Dialog>
										)}
								</div>
							</td>
						</tr>
					))}
				</tbody>
			</table>
		</div>
	);
}

// src/lib/organization/ui/widget/Members.svelte
<script lang="ts">
	import { Shield, ShieldCheck, X } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { Avatar, Tabs } from '@skeletonlabs/skeleton-svelte';

	import InviteForm from './InviteForm.svelte';
	import { callForm } from '$lib/primitives/api/callForm';

	import type { Organization, User } from '$lib/db/schema/types/custom';
	import type { Member, MembersAndInvitations, Role } from '$lib/organization/api/types';
	import { NullDocument } from 'fauna';

	interface Props {
		user: User;
	}

	let { user = $bindable() }: Props = $props();

	let invitations = $derived(user.activeOrganization?.invitations ?? []);

	let isOwnerOrAdmin = $derived(
		user.activeOrganization?.members.some(
			(member) =>
				member.user.id === user.id &&
				['role_organization_owner', 'role_organization_admin'].includes(member.role)
		)
	);

	let group = $state('members');

	let searchQuery = $state('');
	let filteredMembers = $derived(filterMembers(user.activeOrganization!.members));

	let openInviteForm = $state(false);

	let errorMessage = $state('');
	let successMessage = $state('');
	let isLoading = $state(true);

	onMount(async () => {
		if (isOwnerOrAdmin) {
			try {
				const membersAndInvitations = await callForm<MembersAndInvitations>({
					url: '/api/org?/getOrganizationMembersAndInvitations',
					data: { organizationId: user.activeOrganization!.id }
				});

				console.log('membersAndInvitations: ', membersAndInvitations);
				user.activeOrganization!.members = membersAndInvitations.members;
				user.activeOrganization!.invitations = membersAndInvitations.invitations;
			} catch (err) {
				if (err instanceof Error) {
					errorMessage = err.message;
				} else {
					errorMessage = 'Unknown error. Please try again. If it persists, contact support.';
				}
			} finally {
				isLoading = false;
			}
		}
	});

	$inspect('Members org: ', user.activeOrganization!);

	function filterMembers(
		members: {
			user: User;
			role: 'role_organization_owner' | 'role_organization_admin' | 'role_organization_member';
		}[]
	) {
		return members
			.filter(({ user }) =>
				`${user.firstName} ${user.lastName}`.toLowerCase().includes(searchQuery.toLowerCase())
			)
			.sort((a, b) => {
				const roleOrder = {
					role_organization_owner: 0,
					role_organization_admin: 1,
					role_organization_member: 2
				};
				return (
					roleOrder[a.role] - roleOrder[b.role] ||
					a.user.lastName.localeCompare(b.user.lastName) ||
					a.user.firstName.localeCompare(b.user.firstName)
				);
			});
	}

	async function handleUpdateRole(
		userId: string,
		event: Event
		// newRole: 'role_organization_admin' | 'role_organization_member'
	) {
		const select = event.target as HTMLSelectElement;
		if (select) {
			const newRole = select.value as Role;

			try {
				await callForm<Organization>({
					url: '/api/org?/updateMemberRole',
					data: { userId, newRole }
				});

				successMessage = 'Role updated successfully!';
				user.activeOrganization!.members = user.activeOrganization!.members.map((member) =>
					member.user.id === userId ? { ...member, role: newRole } : member
				);
			} catch (err) {
				errorMessage = 'Failed to update role';
				console.error(err);
			}
		}
	}

	async function removeMember(userId: string) {
		try {
			const updatedmembers = await callForm<Array<Member>>({
				url: '/api/org?/removeUserFromOrganization',
				data: { userId }
			});
			successMessage = 'Member removed successfully!';
			user.activeOrganization!.members = updatedmembers;
		} catch (err) {
			errorMessage = 'Failed to remove member';
			console.error(err);
		}
	}

	async function handleRevokeInvitation(invitationId: string) {
		try {
			await callForm<NullDocument>({
				url: '/api/org?/revokeInvitation',
				data: { invitationId }
			});
			successMessage = 'Invitation revoked successfully!';
			user.activeOrganization!.invitations = user.activeOrganization!.invitations.filter(
				(invitation) => invitation.id !== invitationId
			);
		} catch (err) {
			errorMessage = 'Failed to revoke invitation';
			console.error(err);
		}
	}
</script>

{#if isLoading}
	<div class="flex justify-center p-4">
		<div class="animate-pulse">Loading...</div>
	</div>
{:else}
	<Tabs bind:value={group}>
		{#snippet list()}
			<Tabs.Control value="members">Members <span>({filteredMembers.length})</span></Tabs.Control>
			<Tabs.Control value="invitations"
				>Invitations <span>({invitations.length})</span></Tabs.Control
			>
		{/snippet}
		{#snippet content()}
			<Tabs.Panel value="members">
				<div class="p-4">
					<div class="flex gap-3">
						<input
							type="text"
							class="input"
							placeholder="Search members..."
							bind:value={searchQuery}
						/>
						{#if isOwnerOrAdmin}
							<button
								type="button"
								class="btn preset-tonal"
								onclick={() => (openInviteForm = !openInviteForm)}>Invite</button
							>
						{/if}
					</div>

					{#if openInviteForm}
						<div class="relative mt-3">
							<InviteForm bind:user />
							<button
								type="button"
								class="btn-icon preset-tonal absolute top-3 right-3 rounded-full"
								onclick={() => (openInviteForm = false)}
							>
								<X />
							</button>
						</div>
					{/if}

					{#if errorMessage}
						<p class="text-error-500">{errorMessage}</p>
					{/if}
					{#if successMessage}
						<p class="text-success-500">{successMessage}</p>
					{/if}

					<table class="table caption-bottom">
						<thead>
							<tr class="border-surface-300-700 border-b">
								<th class="p-2 text-left">Name</th>
								<th class="p-2 text-left">Email</th>
								<th class="p-2 text-left">Role</th>
								{#if isOwnerOrAdmin}
									<th class="p-2 text-right">Actions</th>
								{/if}
							</tr>
						</thead>
						<tbody>
							{#each filteredMembers as member}
								<tr>
									<td>
										<div class="flex items-center space-x-4">
											<Avatar
												src={member.user.avatar}
												name={`${member.user.firstName} ${member.user.lastName}`}
											/>
											<span class="font-semibold"
												>{member.user.firstName} {member.user.lastName}</span
											>
										</div>
									</td>
									<td>{member.user.primaryEmail}</td>
									<td>
										<div class="flex items-center">
											{#if isOwnerOrAdmin && member.user.id !== user.id && member.role !== 'role_organization_owner'}
												<select
													bind:value={member.role}
													onchange={(event) => handleUpdateRole(member.user.id, event)}
													class="select"
												>
													<option value="role_organization_admin">Admin</option>
													<option value="role_organization_member">Member</option>
												</select>
											{:else if member.role === 'role_organization_owner'}
												<ShieldCheck class="text-primary-500 mr-1 size-4" />
												<span class="font-medium">Owner</span>
											{:else if member.role === 'role_organization_admin'}
												<Shield class="text-primary-400 mr-1 size-4" />
												<span class="font-medium">Admin</span>
											{:else}
												<span>Member</span>
											{/if}
										</div>
									</td>
									<td>
										<div class="flex space-x-2">
											{#if isOwnerOrAdmin && member.user.id !== user.id && member.role !== 'role_organization_owner'}
												<button
													onclick={() => removeMember(member.user.id)}
													class="btn preset-outlined-error-500"
												>
													Remove
												</button>
											{/if}
										</div>
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</Tabs.Panel>
			<Tabs.Panel value="invitations">
				{#if invitations.length == 0}
					<div class="text-surface-600-400 p-8 text-center">
						<p>No pending invitations.</p>
					</div>
				{:else}
					<div class="overflow-x-auto">
						<table class="w-full">
							<thead>
								<tr class="border-surface-300-700 border-b">
									<th class="p-2 text-left">Email</th>
									<th class="p-2 text-left">Role</th>
									<th class="p-2 text-left">Invited By</th>
									{#if isOwnerOrAdmin}
										<th class="p-2 text-right">Actions</th>
									{/if}
								</tr>
							</thead>
							<tbody>
								{#each invitations as invitation}
									<tr class="border-surface-300-700 border-b">
										<td class="p-2">{invitation.email}</td>
										<td class="p-2">
											{#if invitation.role === 'role_organization_owner'}
												<div class="flex items-center">
													<ShieldCheck class="text-primary-500 mr-1 size-4" />
													<span class="font-medium">Owner</span>
												</div>
											{:else if invitation.role === 'role_organization_admin'}
												<div class="flex items-center">
													<Shield class="text-primary-400 mr-1 size-4" />
													<span class="font-medium">Admin</span>
												</div>
											{:else}
												<span>Member</span>
											{/if}
										</td>
										<td class="p-2"
											>{invitation.invitedBy.firstName} {invitation.invitedBy.lastName}</td
										>
										<td class="p-2 text-right">
											<button
												class="btn text-error-500"
												onclick={() => handleRevokeInvitation(invitation.id)}
											>
												Revoke
											</button>
										</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				{/if}
			</Tabs.Panel>
		{/snippet}
	</Tabs>
{/if}
