// nextjs/src/components/organizations/ui/widget/OrganizationSwitcher.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ChevronsUpDown, Plus, Settings, X } from "lucide-react";
import { Avatar } from "@skeletonlabs/skeleton-react";

import { useQuery, useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import CreateOrganization from "./CreateOrganization";

import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/primitives/ui/Popover";
import {
  Modal,
  ModalContent,
  ModalClose,
  ModalTrigger,
} from "@/components/primitives/ui/Modal";

import type { Id } from "@/convex/_generated/dataModel";

/**
 * Organization switcher component that allows switching between organizations,
 * creating new organizations, and accessing organization settings.
 */
export default function OrganizationSwitcher() {
  const router = useRouter();

  // Queries and mutations
  const organizations = useQuery(api.organizations.getUserOrganizations);
  const activeOrganization = useQuery(api.organizations.getActiveOrganization);
  const setActiveOrg = useMutation(api.organizations.setActiveOrganization);

  // State
  const [openSwitcher, setOpenSwitcher] = useState<boolean>(false);
  const [openCreateOrganization, setOpenCreateOrganization] =
    useState<boolean>(false);
  const [openOrganizationProfile, setOpenOrganizationProfile] =
    useState<boolean>(false);

  /**
   * Updates the active organization
   */
  const updateActiveOrg = async (organizationId: Id<"organizations">) => {
    try {
      await setActiveOrg({ organizationId });

      // Close popover and refresh
      setOpenSwitcher(false);
      router.refresh();
    } catch (err) {
      console.error(err);
    }
  };

  /**
   * Temporary LeaveOrganization component (will be implemented separately)
   */
  const LeaveOrganization = ({
    organizationId,
  }: {
    organizationId: Id<"organizations">;
  }) => (
    <button
      onClick={() => console.log("Leave organization:", organizationId)}
      className="btn preset-outlined-error-500 flex gap-2"
    >
      <X size={16} />
      <span>Leave</span>
    </button>
  );

  /**
   * Temporary OrganizationProfile component (will be implemented separately)
   */
  const OrganizationProfile = () => (
    <div className="p-4">
      <h2 className="text-xl font-bold mb-4">Organization Profile</h2>
      <p>This component will be implemented separately.</p>
    </div>
  );

  // Loading state
  if (!organizations) {
    return (
      <div className="animate-pulse h-8 w-40 bg-gray-200 rounded-md"></div>
    );
  }

  // No organizations - just show the create button
  if (organizations.length === 0) {
    return (
      <Modal
        open={openCreateOrganization}
        onOpenChange={setOpenCreateOrganization}
      >
        <ModalTrigger className="btn preset-tonal flex items-center gap-2">
          <Plus size={16} />
          <span>Create Organization</span>
        </ModalTrigger>
        <ModalContent>
          <CreateOrganization />
          <ModalClose />
        </ModalContent>
      </Modal>
    );
  }

  // Has organizations - show the switcher
  return (
    <>
      <Popover
        open={openSwitcher}
        onOpenChange={setOpenSwitcher}
        placement="bottom-end"
      >
        <PopoverTrigger onClick={() => setOpenSwitcher(!openSwitcher)}>
          <div className="flex items-center gap-2">
            <Avatar
              src={activeOrganization?.logo || ""}
              name={activeOrganization?.name || ""}
              size="size-6"
            />
            <span className="text-surface-700-300 text-base font-semibold">
              {activeOrganization?.name}
            </span>
            <ChevronsUpDown size={12} />
          </div>
        </PopoverTrigger>

        <PopoverContent>
          <ul role="list" className="space-y-1">
            <li>
              <div className="rounded-base text-surface-700-300 flex items-center gap-x-3 p-4 text-sm/6 font-semibold">
                <Avatar
                  src={activeOrganization?.logo || ""}
                  name={activeOrganization?.name || ""}
                  size="size-6"
                />
                <span className="text-surface-700-300 text-base font-semibold">
                  {activeOrganization?.name}
                </span>
                {activeOrganization?.role === "role_organization_owner" ||
                activeOrganization?.role === "role_organization_admin" ? (
                  <button
                    onClick={() => {
                      setOpenOrganizationProfile(true);
                      setOpenSwitcher(false);
                    }}
                    className="btn preset-outlined-surface-500 flex gap-2"
                  >
                    <Settings size={16} />
                    <span>Manage</span>
                  </button>
                ) : (
                  activeOrganization && (
                    <LeaveOrganization
                      organizationId={activeOrganization._id}
                    />
                  )
                )}
              </div>
            </li>

            {organizations
              .filter((org) => org && org._id !== activeOrganization?._id)
              .map(
                (org) =>
                  org && (
                    <li key={org._id}>
                      <button
                        onClick={() => updateActiveOrg(org._id)}
                        className="group rounded-base text-surface-700-300 hover:text-primary-600-400 flex gap-x-3 p-4 text-sm/6 font-semibold hover:bg-gray-50 w-full"
                      >
                        <Avatar
                          src={org.logo || ""}
                          name={org.name}
                          size="size-6"
                        />
                        <span className="text-surface-700-300 text-base font-semibold">
                          {org.name}
                        </span>
                      </button>
                    </li>
                  )
              )}

            <li>
              <button
                onClick={() => {
                  setOpenCreateOrganization(true);
                  setOpenSwitcher(false);
                }}
                className="btn preset-tonal flex items-center gap-2 w-full"
              >
                <Plus size={16} />
                <span>Create Organization</span>
              </button>
            </li>
          </ul>
        </PopoverContent>
      </Popover>

      <Modal
        open={openCreateOrganization}
        onOpenChange={setOpenCreateOrganization}
      >
        <ModalContent>
          <CreateOrganization />
          <ModalClose />
        </ModalContent>
      </Modal>

      <Modal
        open={openOrganizationProfile}
        onOpenChange={setOpenOrganizationProfile}
      >
        <ModalContent>
          <OrganizationProfile />
          <ModalClose />
        </ModalContent>
      </Modal>
    </>
  );
}

// src/lib/organization/ui/widget/OrganizationSwitcher.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { ChevronsUpDown, Plus, Settings, X } from 'lucide-svelte';
	import { Avatar, Modal, Popover } from '@skeletonlabs/skeleton-svelte';

	import { callForm } from '$lib/primitives/api/callForm';
	import CreateOrganization from './CreateOrganization.svelte';
	import OrganizationProfile from './OrganizationProfile.svelte';
	import LeaveOrganization from './LeaveOrganization.svelte';

	import type { Organization, User } from '$lib/db/schema/types/custom';

	let user: User | null = $state(JSON.parse(page.data.user ?? null));
	let derivedUser: User | null = $derived(JSON.parse(page.data.user ?? null));

	$effect(() => {
		user = derivedUser;
	});

	let activeOrg = $derived(user?.activeOrganization);
	let orgs = $derived(user?.organizations);

	let openStateSwitcher = $state(false);
	let openStateCreateOrganization = $state(false);
	let openStateOrganizationProfile = $state(false);

	async function updateActiveOrg(organizationId: string) {
		try {
			const org = await callForm<Organization>({
				url: '/api/org?/setActiveOrganization',
				data: { organizationId }
			});
			user!.activeOrganization = org;

			goto('/', { invalidateAll: true });
		} catch (err) {
			console.error(err);
		}

		openStateSwitcher = false;
	}
</script>

{#if user && orgs && orgs.length > 0}
	<Popover
		bind:open={openStateSwitcher}
		positioning={{ placement: 'bottom-end' }}
		triggerBase="btn"
		contentBase="card bg-surface-200-800 max-w-80"
	>
		{#snippet trigger()}
			<div class="flex items-center gap-2">
				<Avatar src={activeOrg!.logo} name={activeOrg!.name} size="size-6" />
				<span class="text-surface-700-300 text-base font-semibold">{activeOrg!.name}</span>
				<ChevronsUpDown size="12" />
			</div>
		{/snippet}
		{#snippet content()}
			<ul role="list" class="space-y-1">
				<li>
					<div
						class="rounded-base text-surface-700-300 flex items-center gap-x-3 p-4 text-sm/6 font-semibold"
					>
						<Avatar src={activeOrg!.logo} name={activeOrg!.name} size="size-6" />
						<span class="text-surface-700-300 text-base font-semibold">{activeOrg!.name}</span>
						{#if user!.roles.some( (role) => ['role_organization_owner', 'role_organization_admin'].includes(role) )}
							<button
								onclick={() => {
									openStateOrganizationProfile = true;
									openStateSwitcher = false;
								}}
								class="btn preset-outlined-surface-500 flex gap-2"
							>
								<Settings size="16" />
								<span>Manage</span>
							</button>
						{:else}
							<LeaveOrganization bind:user={user!} />
						{/if}
					</div>
				</li>

				{#each orgs as org}
					{#if org.id !== activeOrg!.id}
						<li>
							<button
								onclick={() => updateActiveOrg(org.id)}
								class="group rounded-base text-surface-700-300 hover:text-primary-600-400 flex gap-x-3 p-4 text-sm/6 font-semibold hover:bg-gray-50"
							>
								<Avatar src={org!.logo} name={org!.name} size="size-6" />
								<span class="text-surface-700-300 text-base font-semibold">{org!.name}</span>
							</button>
						</li>
					{/if}
				{/each}
				<li>
					<Modal
						bind:open={openStateCreateOrganization}
						triggerBase="btn preset-tonal"
						contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-(--breakpoint-sm) min-w-96"
						backdropClasses="backdrop-blur-xs"
					>
						{#snippet trigger()}
							<Plus size="16" />
							<span>Create Organization</span>
						{/snippet}
						{#snippet content()}
							<CreateOrganization />
						{/snippet}
					</Modal>
				</li>
			</ul>
		{/snippet}
	</Popover>
	<Modal
		bind:open={openStateOrganizationProfile}
		triggerBase="btn preset-tonal"
		contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-(--breakpoint-sm) min-w-96 relative"
		backdropClasses="backdrop-blur-xs"
	>
		{#snippet content()}
			<OrganizationProfile />
			<button
				type="button"
				class="btn-icon preset-tonal absolute top-3 right-3 rounded-full"
				onclick={() => (openStateOrganizationProfile = false)}><X size="16" /></button
			>
		{/snippet}
	</Modal>
{:else if user}
	<Modal
		bind:open={openStateCreateOrganization}
		triggerBase="btn preset-tonal"
		contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-(--breakpoint-sm) min-w-96"
		backdropClasses="backdrop-blur-xs"
	>
		{#snippet trigger()}
			<Plus size="16" />
			<span>Create Organization</span>
		{/snippet}
		{#snippet content()}
			<CreateOrganization />
		{/snippet}
	</Modal>
{/if}
