// nextjs/src/components/user/ui/widget/DeleteUser.tsx
import {
  Modal,
  ModalContent,
  ModalTrigger,
} from "@/components/primitives/ui/Modal";
import { useState } from "react";
import { useAction } from "convex/react";
import { api } from "@/convex/_generated/api";
import { useAuthActions } from "@convex-dev/auth/react";

export default function DeleteUser() {
  const [deleteConfirmationOpen, setDeleteConfirmationOpen] = useState(false);
  const deleteMutation = useAction(api.user.invalidateAndDeleteUser);
  const { signOut } = useAuthActions();

  async function handleConfirm() {
    try {
      await deleteMutation();
      await signOut();
    } catch (error) {
      console.error("Error deleting user:", error);
    }
  }

  function handleCancel() {
    setDeleteConfirmationOpen(false);
  }

  return (
    <Modal
      open={deleteConfirmationOpen}
      onOpenChange={setDeleteConfirmationOpen}
    >
      <ModalTrigger className="btn text-error-500 hover:preset-tonal-error-500">
        Delete account
      </ModalTrigger>
      <ModalContent>
        <header className="flex justify-between">
          <h2 className="h2">Delete your account</h2>
        </header>
        <article>
          <p className="opacity-60">
            Are you sure you want to delete your account? All of your data will
            be permanently deleted.
          </p>
        </article>
        <footer className="flex justify-end gap-4">
          <button
            type="button"
            className="btn preset-tonal"
            onClick={handleCancel}
          >
            Cancel
          </button>
          <button
            type="button"
            className="btn preset-filled-error-500"
            onClick={handleConfirm}
          >
            Confirm
          </button>
        </footer>
      </ModalContent>
    </Modal>
  );
}

// src/lib/user/ui/widget/DeleteUser.svelte
<script lang="ts">
	import { Modal } from '@skeletonlabs/skeleton-svelte';
	import { callForm } from '$lib/primitives/api/callForm';

	let open = $state(false);
	let localError = $state('');

	async function handleConfirm() {
		try {
			await callForm({
				url: '/api/user?/deleteUser'
			});
		} catch (err) {
			if (err instanceof Error) {
				localError = err.message;
			} else {
				localError = 'Unknown error. Please try again. If it persists, contact support.';
			}
		}
	}

	function handleCancel() {
		open = false;
	}
</script>

<Modal
	bind:open
	triggerBase="btn text-error-500 hover:preset-tonal-error-500"
	contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-(--breakpoint-sm)"
	backdropClasses="backdrop-blur-xs"
>
	{#snippet trigger()}
		Delete account
	{/snippet}
	{#snippet content()}
		<header class="flex justify-between">
			<h2 class="h2">Delete your account</h2>
		</header>
		<article>
			<p class="opacity-60">
				Are you sure you want to delete your account? All of your data will be permanently deleted.
			</p>
		</article>
		<footer class="flex justify-end gap-4">
			<button type="button" class="btn preset-tonal" onclick={handleCancel}> Cancel </button>
			<button type="button" class="btn preset-filled-error-500" onclick={handleConfirm}>
				Confirm
			</button>
		</footer>
		{#if localError}
			<p class="text-error-600-400">{localError}</p>
		{/if}
	{/snippet}
</Modal>
