// svelte/src/routes/admin/+page.svelte
<script lang="ts">
	// SvelteKit
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import type { Pathname } from '$app/types';

	// Icons
	import ShieldAlertIcon from '@lucide/svelte/icons/shield-alert';

	// API
	import { useQuery } from 'convex-svelte';
	import { useAuth } from '@mmailaender/convex-better-auth-svelte/svelte';
	import { getAuthContext } from '$lib/auth/context.svelte';

	// Components
	import AdminDashboard from '$lib/admin/ui/AdminDashboard.svelte';

	const { api } = getAuthContext();
	const auth = useAuth();

	// `undefined` while loading, `true`/`false` once resolved.
	const adminResponse = useQuery(api.admin.queries.isCurrentUserAdmin, () =>
		auth.isAuthenticated ? {} : 'skip'
	);
	const isAdmin = $derived(adminResponse?.data);

	// Gating is UX only — the real boundary is `requireAppAdmin` on every admin
	// Convex function. Signed-out visitors go to sign-in and return to /admin.
	$effect(() => {
		if (!auth.isLoading && !auth.isAuthenticated) {
			void goto(resolve(`/signin?redirectTo=${encodeURIComponent('/admin')}` as Pathname));
		}
	});
</script>

{#if auth.isLoading || !auth.isAuthenticated || isAdmin === undefined}
	<!-- Resolving auth or the admin check → a neutral spinner (no content flash). -->
	<div class="flex min-h-[60vh] w-full items-center justify-center p-6">
		<div
			class="border-surface-300-700 size-6 animate-spin rounded-full border-2 border-t-transparent"
			role="status"
			aria-label="Loading"
		></div>
	</div>
{:else if isAdmin === false}
	<!--
		Signed in, but not an application admin.

		Default: a transparent 403 "Access denied" page — the conventional behavior
		for admin tooling, and harmless because every admin Convex function enforces
		access server-side regardless of what this page shows.

		To HIDE that an admin area exists instead (e.g. a public-facing app where
		regular users shouldn't know it's there), replace this block with a 404:
		in a +page.ts/+page.server.ts `load`, `throw error(404, 'Not found')`.
	-->
	<div
		class="mx-auto flex min-h-[60vh] w-full max-w-md flex-col items-center justify-center gap-4 p-6 text-center"
	>
		<ShieldAlertIcon class="size-10 opacity-60" />
		<div>
			<h1 class="h4">Access denied</h1>
			<p class="mt-1 text-sm opacity-60">You don't have permission to view this page.</p>
		</div>
		<a href={resolve('/')} class="btn preset-tonal">Back to home</a>
	</div>
{:else}
	<div class="mx-auto w-full max-w-5xl p-4 sm:p-6">
		<h1 class="h3 mb-4">Admin</h1>
		<AdminDashboard />
	</div>
{/if}

// nextjs/src/app/admin/page.tsx
'use client';

import { useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useConvexAuth, useQuery } from 'convex/react';
import { ShieldAlert } from 'lucide-react';

import { api } from '@/convex/_generated/api';
import AdminDashboard from '@/components/admin/ui/AdminDashboard';

/**
 * `/admin` — the application admin dashboard page.
 *
 * Gating is UX only; the real authorization boundary is the `requireAppAdmin`
 * guard enforced by every admin Convex function. Three outcomes:
 *  - signed out      → redirect to sign-in, returning here afterwards
 *  - signed in, not admin → 403 "Access denied" (see override note below)
 *  - admin           → the dashboard
 */
export default function AdminPage() {
	const router = useRouter();
	const { isAuthenticated, isLoading } = useConvexAuth();

	// `undefined` while loading, `true`/`false` once resolved.
	const isAdmin = useQuery(api.admin.queries.isCurrentUserAdmin, isAuthenticated ? {} : 'skip');

	// Signed-out visitors go to sign-in and are returned to /admin afterwards.
	useEffect(() => {
		if (!isLoading && !isAuthenticated) {
			router.replace(`/signin?redirectTo=${encodeURIComponent('/admin')}`);
		}
	}, [router, isLoading, isAuthenticated]);

	// Resolving auth or the admin check → a neutral spinner (no content flash).
	if (isLoading || !isAuthenticated || isAdmin === undefined) {
		return (
			<div className="flex min-h-[60vh] w-full items-center justify-center p-6">
				<div
					className="border-surface-300-700 size-6 animate-spin rounded-full border-2 border-t-transparent"
					role="status"
					aria-label="Loading"
				/>
			</div>
		);
	}

	// Signed in, but not an application admin.
	//
	// Default: a transparent 403 "Access denied" page — the conventional behavior
	// for admin tooling, and harmless because every admin Convex function enforces
	// access server-side regardless of what this page shows.
	//
	// ── To HIDE that an admin area exists instead (e.g. a public-facing app where
	//    regular users shouldn't know it's there), swap this block for Next's 404:
	//        import { notFound } from 'next/navigation';
	//        if (isAdmin === false) notFound();
	if (isAdmin === false) {
		return (
			<div className="mx-auto flex min-h-[60vh] w-full max-w-md flex-col items-center justify-center gap-4 p-6 text-center">
				<ShieldAlert className="size-10 opacity-60" />
				<div>
					<h1 className="h4">Access denied</h1>
					<p className="mt-1 text-sm opacity-60">
						You don&apos;t have permission to view this page.
					</p>
				</div>
				<Link href="/" className="btn preset-tonal">
					Back to home
				</Link>
			</div>
		);
	}

	return (
		<div className="mx-auto w-full max-w-5xl p-4 sm:p-6">
			<h1 className="h3 mb-4">Admin</h1>
			<AdminDashboard />
		</div>
	);
}
