// nextjs/src/components/admin/ui/AdminButton.tsx
'use client';

import Link from 'next/link';
import { Shield } from 'lucide-react';

import { AUTH_CONSTANTS } from '@/convex/auth.constants';
import { useIsAppAdmin } from '@/lib/auth/hooks';
import { ADMIN_ROUTE } from '@/components/admin/utils/admin.constants';

/**
 * Optional navigation link to the `/admin` dashboard. Renders nothing unless the
 * `admin` feature is enabled and the current user is an application admin.
 *
 * This is **not** mounted in the default layout — the admin dashboard is a route
 * (`/admin`) that operators navigate to directly. Drop this link into your own
 * nav/sidebar if you want a visible entry point.
 */
export default function AdminButton({ className }: { className?: string }) {
	const isAppAdmin = useIsAppAdmin();

	if (!AUTH_CONSTANTS.admin || !isAppAdmin) return null;

	return (
		<Link
			href={ADMIN_ROUTE}
			className={className ?? 'btn preset-tonal gap-2'}
			aria-label="Open admin dashboard"
		>
			<Shield className="size-4" />
			<span>Admin</span>
		</Link>
	);
}

// svelte/src/lib/admin/ui/AdminButton.svelte
<script lang="ts">
	// SvelteKit
	import { resolve } from '$app/paths';

	// Icons
	import ShieldIcon from '@lucide/svelte/icons/shield';

	// Constants & API
	import { getAuthContext } from '$lib/auth/context.svelte';
	import { useIsAppAdmin } from '$lib/admin/api/admin.svelte';

	let { class: className }: { class?: string } = $props();

	const { authConstants } = getAuthContext();
	const admin = useIsAppAdmin();
</script>

<!--
	Optional navigation link to the `/admin` dashboard. Renders nothing unless the
	`admin` feature is enabled and the current user is an application admin. Not
	mounted in the default layout — drop it into your own nav if you want a visible
	entry point. The admin dashboard is the `/admin` route.
-->
{#if authConstants.admin && admin.isAppAdmin}
	<a
		href={resolve('/admin')}
		class={className ?? 'btn preset-tonal gap-2'}
		aria-label="Open admin dashboard"
	>
		<ShieldIcon class="size-4" />
		<span>Admin</span>
	</a>
{/if}
